### ISSUE TITLE
Cryptococcus NTR: competitive fitness phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#103]
NTR
1)	competitive fitness phenotype
APO cross-refs:
id: APO:0000110
name: competitive fitness
namespace: observable
alt_id: YPO:0000110
def: "The ability of a mutant strain to grow or survive under conditions of direct competition with wild type or other mutants." [SGD:curators]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: phenotypeslim_cerevisiae
subset: SGD
is_a: APO:0000216 ! fitness

2)	altered competitive fitness (is_a competitive fitness phenotype)
3)	increased competitive fitness (is_a altered competitive fitness)
4)	decreased competitive fitness (is_a altered competitive fitness)
5)	abolished competitive fitness (is_a decreased competitive fitness)

**Comment by dianeoinglis** [comment]
This term is exclusively an in vivo assay for Cryptococcus and is not in vivo for S. cerevisiae that this APO term is used for. This phenotype belongs with other " competitive growth" or competitive colonization" terms in a different ticket.

Thank you,

Diane

**Comment by Achchuthan** [comment]
Okay, I'll close this issue
