### ISSUE TITLE
Cryptococcus NTR: endocytosis phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#104]
NTR
1)	endocytosis phenotype
xref: GO:0006897 " endocytosis"	

APO cross-refs:
id: APO:0000075
name: endocytosis
namespace: observable
alt_id: YPO:0000075
def: "The uptake and delivery of external materials or membrane constituents by the invagination of a small region of the plasma membrane to form a new membrane-bounded vesicle." [SGD:curators]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000073 ! intracellular transport

2)	altered endocytosis (is_a endocytosis phenotype)
3)	increased endocytosis (is_a altered endocytosis)
4)	decreased endocytosis (is_a altered endocytosis)
5)	abolished endocytosis (is_a decreased endocytosis)
6)	delayed endocytosis (is_a altered endocytosis)

**Comment by dianeoinglis** [comment]
This term is good to go.

Diane

**Comment by Jguzman210** [comment]
Endocytosis terms

1) OMP:0005261	endocytosis phenotype
2)OMP:0005262	altered endocytosis
3) OMP:0005263	increased endocytosis
4) OMP:0005264	decreased endocytosis
5) OMP:0005265	abolished endocytosis
6) OMP:0005266	delayed onset of endocytosis

**Comment by Achchuthan** [comment]
Thanks a lot for your help!
