### ISSUE TITLE
Cryptococcus NTR: endomembrane system morphology phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#105]
NTR
1)	endomembrane system morphology phenotype
xref: GO:0012505 " endomembrane system"	

APO cross-refs:
id: APO:0000303
name: endomembrane system morphology
namespace: observable
def: "The size, shape, or appearance of components of the endomembrane system, which includes the nuclear envelope, endoplasmic reticulum, Golgi apparatus, peroxisomes, vacuoles, and endocytic and exocytic vesicles." [PMID:19121819, SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000226 ! subcellular morphology

2)	altered endomembrane system morphology (is_a endomembrane system morphology phenotype)

**Comment by dianeoinglis** [comment]
This term is fine to assign an OMP ID.

Diane

**Comment by Jguzman210** [comment]
1) OMP:0005270	endomembrane system morphology phenotype
2) OMP:0005271	altered endomembrane system morphology
