### ISSUE TITLE
Cryptococcus NTR: filamentous growth phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#106]
NTR
1)	filamentous growth phenotype
xref: GO:0030447 " filamentous growth"	

APO cross-refs:
id: APO:0000027
name: filamentous growth
namespace: observable
alt_id: YPO:0000027
def: "Growth in a threadlike, filamentous shape." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: phenotypeslim_cerevisiae
subset: SGD
is_a: APO:0000023 ! development

2)	altered filamentous growth (is_a filamentous growth phenotype)
3)	increased filamentous growth (is_a altered filamentous growth)
4)	decreased filamentous growth (is_a altered filamentous growth)
5)	abolished filamentous growth (is_a decreased filamentous growth)

**Comment by Jguzman210** [comment]
TR with OMP accesion # 
1) filamentous growth phenotype: OMP:0005243	
2) altered filamentous growth (is_a filamentous growth phenotype) OMP:0005244
3) OMP:0005245	increased filamentous growth
4) OMP:0005246	decreased filamentous growth
5) OMP:0005247	abolished filamentous growth

**Comment by Achchuthan** [comment]
Thanks a lot Jesus for the terms!
