### ISSUE TITLE
Cryptococcus NTR: golgi morphology phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#107]
NTR
1)	golgi morphology phenotype
xref: GO:0005794 " Golgi apparatus"	

APO cross-refs:
id: APO:0000243
name: Golgi morphology
namespace: observable
alt_id: YPO:0000243
def: "The size, shape or appearance of the Golgi apparatus or its parts." [SGD:RSN]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000303 ! endomembrane system morphology

2)	altered golgi morphology (is_a golgi morphology phenotype)

**Comment by dianeoinglis** [comment]
This subcellular phenotype is good to go.

Thanks,
Diane

**Comment by Jguzman210** [comment]
1) golgi morphology phenotype OMP:0005238

2) altered golgi morphology (is_a golgi morphology phenotype) OMP:0005239
