### ISSUE TITLE
Cryptococcus NTR: altered liquid culture morphology

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#115]
NTR

altered liquid culture morphology (is_a OMP:0000177! liquid culture morphology phenotype
)

**Comment by dianeoinglis** [comment]
The notes associated with the 3 phenotype annotations are:

mutant cells grew in clumps in liquid culture rather than as dispersed single or budded cells
mutant cells grow in large clusters instead of as dispersed cells
mutants show increased clumping after growth overnight in YPD medium

"flocculation" is appropriate as a child term of "liquid culture morphology phenotype"

Diane

**Comment by Achchuthan** [comment]
Diane, flocculated liquid culture already exists as a child term

**Comment by dianeoinglis** [comment]
Hello,

"altered liquid culture morphology" is a descriptive term. I need the altered biological process term "flocculation phenotype."

altered flocculation phenotype
increased flocculation phenotype
decreased flocculation phenotype
abolished flocculation phenotype

GO:0000128 flocculation 
def: The reversible, non-sexual aggregation of single-celled organisms in suspension to form aggregates of many cells known as flocs." [GOC:jl, GOC:vw, PMID:21114594, PMID:8740415]

APO:0000065 flocculation
def: "Adhesion and aggregation of cells in liquid culture to produce clumps of cells." [SGD:mcc]

Thank you!
Diane

**Comment by dianeoinglis** [comment]
The process terms would be much appreciated.

altered flocculation phenotype
increased flocculation phenotype
decreased flocculation phenotype
abolished flocculation phenotype

Thank you!
Diane

**Comment by dsiegele** [comment]
Diane, Sorry for the delay. Jesus was waiting for me to review his work before adding the terms to the ontology.  Debby 

OMP:0000178	flocculation phenotype (changed name of already existing term): A liquid culture morphology phenotype where cells aggregate together in suspension to form clumps of many cells known as flocs.

OMP:0007468	abolished flocculation
OMP:0007464	absence of flocculation
OMP:0007465	altered flocculation
OMP:0007467	decreased flocculation
OMP:0007466	increased flocculation
OMP:0007463	presence of flocculation

**Comment by dianeoinglis** [comment]
Wonderful. Thank you!

**Comment by dsiegele** [comment]
Jesus added the terms to the ontology.

**Comment by dsiegele** [comment]
The terms were added to the omp-edit.obo file on 9-12-2016, but they aren't loaded on the OMPwiki. I reopened the issue while I check on this.

**Comment by dsiegele** [comment]
Jim fixed the script problem that prevented new terms from being added to OMPwiki.
