### ISSUE TITLE
Cryptococcus NTR: mating projection morphology phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#117]
NTR
1)	mating projection morphology phenotype
APO cross-refs:
id: APO:0000223
name: mating projection morphology
namespace: observable
alt_id: YPO:0000223
def: "The outward appearance or shape of the mating projection." [SGD:RSN]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000050 ! cellular morphology

2)	altered mating projection morphology (is_a mating projection morphology phenotype)

**Comment by dianeoinglis** [comment]
Please cancel this request. This term is not necessary. Mating projections are used in other fungi. Cryptococcus mating projections are hyphal filaments and will be handled in a different term request.

Thank you,
Diane

**Comment by Achchuthan** [comment]
I am closing this issue as it is not necessary after Diane's comments.
