### ISSUE TITLE
Cryptococcus NTR: nuclear position phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#127]
NTR

1)	nuclear position phenotype

APO cross-refs:
id: APO:0000118
name: nuclear position
namespace: observable
alt_id: YPO:0000118
def: "The location of the nucleus or nuclei within a cell or between separating cells." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000296 ! organelle distribution

2)	altered nuclear position (is_a nuclear position phenotype)

**Comment by dsiegele** [comment]
Made the requested terms. Please check definitions.

Thank you!

[Term]
id: OMP:0007344
name: nuclear position phenotype
def: "A cell morphology phenotype related to the location of a nucleus or nucleus within a cell or between separating cells." [APO:0000118, OMP:DAS]
comment: This term was created to organize terms beneath it in the ontology. We recommend that it not be used for annotation unless an appropriate child term cannot be found or requested.
is_a: OMP:0000071 ! cell morphology phenotype

[Term]
id: OMP:0007345
name: altered nuclear position
def: "A nuclear position phenotype where the location of the nucleus or nuclei within a cell or between separating cells is altered relative to a designated control." [OMP:DAS]
is_a: OMP:0007344 ! nuclear position phenotype
intersection_of: OMP:0007344 ! nuclear position phenotype
intersection_of: has_quality OMP:0007189 ! altered_relative_to

**Comment by Achchuthan** [comment]
Thanks a lot!
