### ISSUE TITLE
Cryptococcus NTR: phospholipase B secretion phenotype -- secreted protein phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#128]
NTR

1)  phospholipase B secretion phenotype (is_a protein secretion phenotype)

2)  altered phospholipase B secretion (is_a phospholipase B secretion phenotype)

**Comment by dianeoinglis** [comment]
This should be a child term for "protein secretion phenotype"

Diane

**Comment by Achchuthan** [comment]
Thanks Diane. Protein secretion phenotype is not yet in OMP either and a ticket had been created. The issue ticket number is #130

**Comment by Jguzman210** [comment]
Does this need to have an independent term or can we use a general term and place the UniProt accession for phospholipase B in the annotation extension field?

**Comment by Achchuthan** [comment]
Thanks Jesus. I think your idea is better! If we are to create new term for each protein that we find secreted, this will expand the ontology many-fold.

I would suggest creating  a term "enzyme secretion" as a child term of "protein secretion" (issue ticket #130) and we could add "Phospholipase B" as a synonym in the extension field. I think we just add the name of gene and gene symbol and better not add UniProt accession for the term to be valid for the respective enzyme from all species?

1. Enzyme secretion phenotype (is_a: protein secretion phenotype)
Xref: synonym: " Phospholipase B1 " NARROW [Symbol: PLB1]
2. Altered enzyme secretion (is_a: enzyme secretion phenotype)
3. Increased enzyme secretion (is_a: altered enzyme secretion)
4. Decreased enzyme secretion (is_a: altered enzyme secretion)
5. Abolished enzyme secretion (is_a: decreased enzyme secretion)

**Comment by dsiegele** [comment]
Before we make any terms for secretion of specific classes of proteins, we want to think about whether dividing secreted proteins into classes will be useful, and, if so, what are other possible classes? Please send feedback.

**Comment by dsiegele** [comment]
Why we want to use the UNIProtKB accession: Our plan for OMP is to make annotations to strains. Then from the strain pages, pull together all the phenotypes associated with a particular gene and display those on gene pages. A single gene page would actually be for a pan gene and would include all the orthologs in a particular taxonomic unit. For example, phenotypes related to E. coli lacZ would be on one page regardless of which strain or substrain the original annotation came from.

**Comment by Achchuthan** [comment]
Thanks a lot for clarification on these issues. I am also unsure whether we need child terms for different classes of proteins under 'protein secretion phenotype'. As far as the Cryptococcus curation is concerned, the only specific case we have for phenotype curation is Phospholipase B1 secretion. I am happy with Phospholipase B1 added as a narrow synonym either to 'protein secretion phenotype' or one of its child terms, so we can provide this information in extension field.

**Comment by dsiegele** [comment]
Protein secretion phenotypes are for the process of protein secretion. I think what we need to make is a branch for secreted protein phenotypes, which would have children:

presence of a secreted protein
absence of a secreted protein
altered presence of a secreted protein
.....increased amount of a secreted protein
.....decreased amount of a secreted protein
..........abolished secreted protein (this sounds awkward--we can edit it)

What do you think?

**Comment by Achchuthan** [comment]
Thanks Debby! I think secreted protein phenotype is useful, where you can specify the name of the protein in the annotation extension as the narrow synonym! Can we say "abolished presence of a secreted protein" instead of "abolished secreted protein"?

**Comment by dsiegele** [comment]
abolished presence of a secreted protein sounds good. I didn't like abolished secreted protein, but hadn't thought of a replacement. Thank you for the suggestion!

**Comment by dianeoinglis** [comment]
Could "abolished secretion of protein x" be considered? To say that a secreted protein is abolished is not accurate for the phenotype that was captured for Cryptococcus. That phrasing would included abolished a secreted protein that failed to be secreted but may be stuck in the Golgi or somewhere.

Thank you!
Diane

**Comment by dianeoinglis** [comment]
Phospholipases are a family of secreted and cytolic enzymes.  Secretion of Phospholipase B is a virulence determinant in several species of fungal pathogens thought to enable the fungal cells to invade host tissues and cause to disease. When secretion of this enzyme is impaired, the enzyyme cannot digest host tissues and virulence is impacted.  I agree that we do not need terms for every secreted protein but this secreted protein is important to distinguish from the cytosolic phospholipases and this particular enzyme deserves its own term. 

The APO auto-replaces the word "protein" in this term is to form "Phospholipase B1 secretion." If the secretion process fails to deliver this enzyme oiutside the microbial, the enzyme cannot perform its function to interact with host tissues and impairs virulence. The "presence" or "amount" of the secreted protein is not the relevant property of interest. It is the location of the secreted form of Phospholipase B that impacts virulence. If protein secretion is impaired, the amount of this enzyme is not the issue. The abundance of the secreted form of Phospholipase B may not change if Phospholipase B remains in the cytosol. 

I wonder if "protein localization by secretion" and "Phospholipase B localization by secretion" may be term for this phenotype.  When curation was limited to terms in the APO (designed for curation of S. cerevisiae) I had to make do with terms created by a higher power and serve as placeholders until a more accurate term is available for use. Given the importance of Phospholipase secretion as a major virulence determinant in fungal pathogens, it is reasonable for this specific protein to have its own dedicated term. 

Comments?

Diane
