### ISSUE TITLE
Cryptococcus NTR: protein secretion phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#130]
1) NTR

Arrested protein secretion (is_a: OMP:0007346! protein secretion phenotype)

2) Xref

protein secretion phenotype
xref: GO:0009306 " protein secretion"
APO cross-refs:
id: APO:0000078
name: protein secretion
namespace: observable
alt_id: YPO:0000078
def: "Transport of proteins out of the cell by fusion of a membrane-bounded vesicle containing the proteins by fusion of the vesicle with the plasma membrane." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
synonym: "exocytosis" RELATED []
is_a: APO:0000129 ! protein transport

**Comment by Achchuthan** [comment]
Sorry! I see this term already exists in OMP. It's  my mistake. Would be great if APO term is cross-referenced?

xref: GO:0009306 " protein secretion"
APO cross-refs:
id: APO:0000078
name: protein secretion
namespace: observable
alt_id: YPO:0000078
def: "Transport of proteins out of the cell by fusion of a membrane-bounded vesicle containing the proteins by fusion of the vesicle with the plasma membrane." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
synonym: "exocytosis" RELATED []
is_a: APO:0000129 ! protein transport

**Comment by dsiegele** [comment]
APO:0000078 def: "Transport of proteins out of the cell by fusion of a membrane-bounded vesicle containing the proteins by fusion of the vesicle with the plasma membrane." [SGD:mcc]

I added APO:0000078 as a narrow synonym of OMP:0007346 protein secretion phenotype. I did this because in bacteria  protein secretion usually doesn't involve fusion of vesicles with the plasma membrane.

**Comment by Achchuthan** [comment]
Thanks a lot Debby for adding as synonym. This makes sense!

**Comment by dsiegele** [comment]
I added exocytosis as a narrow synonym of protein secretion phenotype.

**Comment by dsiegele** [comment]
What would the definition of 'arrested protein secretion' be?

**Comment by Achchuthan** [comment]
Arrested protein secretion phenotype is an altered protein secretion phenotype where protein secretion was not observed in a given time period relative to a designated control.

**Comment by dsiegele** [comment]
In other OMP terms, we have called phenotypes like this decreased protein secretion and abolished protein secretion. Would that be OK?

**Comment by Achchuthan** [comment]
You're right Debby. As I read the decreased protein secretion definition, it describes the timing as well! So, this sounds good!

**Comment by dianeoinglis** [comment]
When SGD (Saccharomyces Genome Database) uses the APO term "protein secretion", a "Reporter" field is ALWAYS  used to name the  specific protein or fusion protein is the readout such as "heterologous B. licheniformis alpha-amylase," "precursor carboxypeptidase Y," "alpha-factor," etc.

CGD (Candida Genome Database) is less consistent at indicating a reporter. But Candida species have families of secreted proteins such as secreted aspartyl protease (SAP genes or SAPs) and lipases, some of which are important for virulence. Sometimes "secreted aspartyl protease" will be recorded as the Reporter and other times "secreted aspartyl protease" or "secreted aspartyl protease activity" will be in the "Details" field where curators can add free text, depending whether the assay measured protein or protein activity..
http://www.candidagenome.org/cgi-bin/phenotype/phenotype.pl?observable=protein%20secretion

AspGD (Aspergillus Genome Database) also uses the Reporter field or the Details field.
http://www.aspergillusgenome.org/cgi-bin/phenotype/phenotype.pl?observable=protein%20secretion

This term is a child of APO "protein transport" which is somewhat restrictive and most often the specific protein recorded as the reporter, is actually a readout for the process of "exocytosis." Exocytosis is referenced as "synonym: "exocytosis" RELATED []"but, in my opinion, "exocytosis" is preferable as the "term name" and should be a parent of terms for siblings "protein secretion" and "non-protein secretion." Cryptococcus synthesizes "glucuronoxylomannan" which is the major sugar component of the capsule. Glucuronoxylomannan is secreted by exocytosis but the structure of the APO precludes a term for non-protein exocytosis by its placement under "protein transport."

I think the actual term request should be "exocytosis phenotype" with "protein secretion phenotype" and either "glucuronoxylomannan secretion phenotype" or just "carbohydrate secretion phenotype" as child terms of "exocytosis phenotype." As I commented previously, some proteins are so important to the biology of the organism they deserve a specific term such as "secreted phospholipase B secretion phenotype."

Thoughts or comments?
Diane
