### ISSUE TITLE
Cryptococcus NTR: pseudohyphal growth phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#131]
NTR

1)	pseudohyphal growth phenotype
xref: GO:0007124 " pseudohyphal growth"
APO cross-refs:
id: APO:0000029
name: pseudohyphal growth
namespace: observable
alt_id: YPO:0000029
def: "Growth in a pattern that occurs in conditions of nitrogen limitation and abundant fermentable carbon source. Cells become elongated, switch to a unipolar budding pattern, remain physically attached to each other, and invade the growth substrate." [SGD:krc]
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000027 ! filamentous growth

2)	altered pseudohyphal growth (is_a pseudohyphal growth phenotype)
3)	increased pseudohyphal growth (is_a altered pseudohyphal growth)
4)	decreased pseudohyphal growth (is_a altered pseudohyphal growth)

**Comment by dianeoinglis** [comment]
This term needs a modified definition for broader applicability and the parent term needs to be discussed. Can we put this on hold and discuss "growth" and "growth patterns" in another ticket?

Diane

**Comment by Achchuthan** [comment]
I'm closing this issue!
