### ISSUE TITLE
Cryptococcus NTR: hyperosmotic stress resistance phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#132]
NTR

1)	hyperosmotic stress resistance phenotype
APO cross-refs:
id: APO:0000204
name: hyperosmotic stress resistance
namespace: observable
alt_id: YPO:0000204
def: "The level of resistance to high osmolarity." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
synonym: "resistance to hyperosmotic stress" EXACT []
is_a: APO:0000082 ! osmotic stress resistance
2)	presence of hyperosmotic stress resistance (is_a hyperosmotic stress resistance phenotype) 
3)	absence of hyperosmotic stress resistance (is_a hyperosmotic stress resistance phenotype)
4)	altered hyperosmotic stress resistance (is_a hyperosmotic stress resistance phenotype)
5)	increased hyperosmotic stress resistance (is_a altered hyperosmotic stress resistance)
6)	decreased hyperosmotic stress resistance (is_a altered hyperosmotic stress resistance)

**Comment by dianeoinglis** [comment]
alternatively "growth in high osmolarity conditions" ???
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3889573/

Diane

**Comment by dianeoinglis** [comment]
Do away with the assumption of "stress."

**Comment by Achchuthan** [comment]
No need for this issue. This issue is merged with issue #134
