### ISSUE TITLE
Cryptococcus NTR: hypoxic growth phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#133]
NTR

1)	hypoxic growth phenotype (is_a anaerobic growth phenotype)
2)	altered hypoxic growth (is_a hypoxic growth phenotype)
3)	increased hypoxic growth (is_a altered hypoxic growth)
4)	decreased hypoxic growth (is_a altered hypoxic growth)

**Comment by dianeoinglis** [comment]
hypoxia is not always a stress in fungi. Some fungal species are facultative (or obligate) anaerobes. Hypoxia is related to anaerobic growth. I think a more concise term might be "hypoxic growth phenotype."

Anaerobic growth in S. cerevisiae is most often studied on a non-fermentable carbon source. Perhaps anaerobic growth phenotype may be a parent of hypoxic growth. The term "stress" is an assumption and is relative to the species of fungus. I'd like to do away with the word "stress" in this term.

Diane

**Comment by Achchuthan** [comment]
Thanks Diane. I agree and I have added anaerobic growth phenotype as a parent term above. This term is not yet added in OMP and I am referencing it to an earlier issue added by me: #92

**Comment by dsiegele** [comment]
Hypoxia is a condition where O2 levels are >0 but <20% (atmospheric O2 levels). Is this correct? I would consider this a child of aerobic growth, not anaerobic growth.

**Comment by Achchuthan** [comment]
That's correct! We shall use the definition from GO:  "Decline in O2 levels below normoxic levels of 20.8 - 20.95%"? 

Thanks for your help.

Best wishes,
Achchuthan

**Comment by dianeoinglis** [comment]
Thank you Debby and Achchuthan. That is a great point and aerobic growth is a better parentage for the term!

Diane

**Comment by Jguzman210** [comment]
TR with accesion #s
1) OMP:0005254	hypoxic growth phenotype
2) OMP:0005257	altered hypoxic growth
3) OMP:0005258	increased hypoxic growth rate
4) OMP:0005259	decreased hypoxic growth rate
