### ISSUE TITLE
Cryptococcus NTR: growth under altered osmolarity phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#134]
NTR

1)  osmotic stress resistance phenotype
APO cross-refs:
id: APO:0000082
name: osmotic stress resistance
namespace: observable
alt_id: YPO:0000082
def: "The level of resistance to high or low osmolarity." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
synonym: "resistance to osmotic stress" EXACT []
is_a: APO:0000087 ! resistance to chemicals

2)  presence of osmotic stress resistance (is_a osmotic stress resistance phenotype) 
3)  absence of osmotic stress resistance (is_a osmotic stress resistance phenotype)
4)  altered osmotic stress resistance (is_a osmotic stress resistance phenotype)
5)  increased osmotic stress resistance (is_a altered osmotic stress resistance)
6)  decreased osmotic stress resistance (is_a altered osmotic stress resistance)

**Comment by dianeoinglis** [comment]
Let's do away with "stress" part of this term. "osmolarity" should be a parent term for "growth in/under  high osmolarity"

Diane

**Comment by Achchuthan** [comment]
Okay, updated request is as follows:

NTR

1) Osmolarity
Xref: PATO:0001655 " osmolarity"

2) High osmolarity
Xref: PATO:0001657 " increased osmolarity"
is_a: osmolarity phenotype

3) Low osmolarity
Xref: PATO:0001656 " decreased osmolarity"
is_a: osmolarity phenotype

4) growth under high osmolarity phenotype
is_a: osmolarity phenotype
is_a: high osmolarity phenotype
APO cross-refs:
id: APO:0000082
name: osmotic stress resistance
namespace: observable
alt_id: YPO:0000082
def: "The level of resistance to high or low osmolarity." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
synonym: "resistance to osmotic stress" EXACT []
is_a: APO:0000087 ! resistance to chemicals

5) presence of growth under high osmolarity (is_a growth under high osmolarity phenotype)
6) absence of growth under high osmolarity (is_a growth under high osmolarity phenotype)
7) altered growth under high osmolarity (is_a growth under high osmolarity phenotype)
8) increased growth under high osmolarity (is_a altered growth under high osmolarity)
9) decreased growth under high osmolarity (is_a altered growth under high osmolarity)

Thanks,
Achchuthan

**Comment by Jguzman210** [comment]
Do you happen to know what is the osmolarity range for normal growth in Cryptococcus? Also when using the term "high Osmolarity" do we mean in the higher range of normal or outside of normal.

Thank you

**Comment by dsiegele** [comment]
Please give feedback on the definitions of the requested terms. If they're OK, we will add them to OMP.

growth under high osmolarity phenotype (is_a solute and water activity growth range phenotype) def: A growth range phenotype relating to the ability of a microbe to grow and proliferate when the osmolarity of the medium is higher than the osmolarity that allows optimal growth.

	presence of growth under high osmolarity (is_a growth under high osmolarity phenotype) def: A growth under high osmolarity phenotype where a microbe is capable of growth and proliferation under high osmolarity. 

	absence of growth under high osmolarity (is_a growth under high osmolarity phenotype)  def: A growth under high osmolarity phenotype where a microbe cannot grow and proliferate under high osmolarity.

	altered growth under high osmolarity (is_a growth under high osmolarity phenotype)  def: A growth under high osmolarity phenotype where growth and proliferation of a microbe under high osmolarity is altered relative to a designated control. 

		increased growth under high osmolarity (is_a altered growth under high osmolarity) def: An altered growth under high osmolarity phenotype where growth and proliferation under high osmolarity is increased relative to a designated control.

		decreased growth under high osmolarity (is_a altered growth under high osmolarity) def: An altered growth under high osmolarity phenotype where growth and proliferation under high osmolarity is decreased relative to a designated control.

			absence of growth under high osmolarity (is_a decreased growth under high osmolarity) def: A decreased growth under high osmolarity where growth and proliferation under high osmolarity is abolished.

**Comment by dianeoinglis** [comment]
These terms look fine to me. High osmolarity relative to the optimum for an organism is generally considered a "stress." The exception is the use of higher than normal amounts of sorbitol to rescue cells with cell wall defects. In this case, high sorbitol is considered an osmotic support and can rescue some mutations that impact the cell wall. This was the basis for preferring the more general "growth under high osmolarity" term. Please proceed to add these terms.
Thanks!
Diane

**Comment by dsiegele** [comment]
Umbrella term: OMP:0007516	growth under high osmolarity phenotype

OMP:0007518	absence of growth under high osmolarity
.....OMP:0007522 abolished growth under high osmolarity

OMP:0007517 presence of growth under high osmolarity

OMP:0007519	altered growth under high osmolarity
.....OMP:0007521 decreased growth under high osmolarity
...............OMP:0007522 abolished growth under high osmolarity
.....OMP:0007520 increased growth under high osmolarity

Also made OMP:0007523 altered growth range phenotype, which is a child of altered microbial phenotype.

**Comment by dianeoinglis** [comment]
ok. works for me.
