### ISSUE TITLE
Cryptococcus NTR: delayed virulence phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#144]
NTR

1)	delayed virulence (is_a: OMP:0000098 ! altered virulence)

**Comment by dianeoinglis** [comment]
Hi Achchuthan, Debby and all,

Let's discuss this one further. This group of phenotypes has several important issues to deal with and is a MAJOR problem in the APO. It is the biggest problem with the APO that misconstrues the whole viruelence/pathogenesis issue. This phenotype is why the OMP is needed and the APO is problematic. If all the other terms have been assigned and this is the only one left, I recently came home from the hospital but would turn over in my grave if this was treated as it was in the APO. 

"Delayed"** is not a good qualifier for a process like virulence. Please refer to "Cryptococcus virulence and virulence trait phenotypes Ticket #67." Let's refer back to the ticket/issue that I started previously for virulence and work through them. 

These terms are seriously impacted by host species (rabbit, mouse or flies/worms), mouse strain background, route of infection, lethal vs. sublethal innoculation and whether the observation is CFU or host survival. This is a MAJOR phenotype and a discussion on what qualifiers/descriptives should be part of the term itself and which will be entered as an additional field. 

I actually question the use of the word "virulence" at all and want to consider the actual observation "lethality..." There are papers still to be checked for whether "virulence" means less CFU or "killing of the hosts."

Be still my adrenaline-pumped heart!!!

Diane

**Comment by dianeoinglis** [comment]
Let's cancel and close this ticket and discuss virulence terms on another ticket.

Thanks,
Diane

**Comment by Achchuthan** [comment]
Okay, I'' close this issue!

Thanks,
Achchuthan
