### ISSUE TITLE
Cryptococcus Compounds Xref: purine/pyrimidine requirement phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#145]
OMP:0007039 ! purine/pyrimidine requirement

Xref
1)	synonym: " adenine " NARROW [CHEBI:16708]
2)	synonym: " uracil " NARROW [CHEBI:17568]

**Comment by dsiegele** [comment]
Added requested synonyms: adenine requirement and uracil requirement.
