### ISSUE TITLE
Cryptococcus Compounds Xref: amino acid requirement phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#146]
OMP:0007038 ! amino acid requirement

Xref
1)	synonym: " homocysteine " NARROW [CHEBI:17230]
2)	synonym: " isoleucine " NARROW [CHEBI:24898]
3)	synonym: " methionine " NARROW [CHEBI:16811]
4)	synonym: " valine " NARROW [CHEBI:27266]

**Comment by dsiegele** [comment]
Made requested narrow synonyms for amino acid requirement.
