### ISSUE TITLE
Cryptococcus Compounds Xref: aminopyrimidine resistance phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#148]
OMP:0000331 ! aminopyrimidine resistance phenotype

Xref
1)	synonym: " 5-flucytosine " NARROW [CHEBI:5100]

**Comment by dianeoinglis** [comment]
Can "synonym: " 5-flucytosine " NARROW [CHEBI:5100]" be made into a child term of aminopyrimidine resistance phenotype or "growth on aminopyrimidine phenotype?"

Diane

**Comment by dsiegele** [comment]
One of the ways that resistance to an antimicrobial compound is detected is by the ability of an organism to grow in the presence of that compound. I don't see the need for an additional term. Am I missing something? do we need to expand the definition or add an explanation in the comments?

In bacteriology, the construct "growth on aminopyrimidine" would indicate that the organism was using an aminopyrimidine as a nutrient, but I don't think that is what you mean is it?

**Comment by Jguzman210** [comment]
added the synonym
