### ISSUE TITLE
Cryptococcus Compounds Xref: macrolide resistance phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#149]
OMP:0000321 ! macrolide resistance phenotype

Xref
1)	synonym: " amphotericin B " NARROW [CHEBI:2682]
2)	synonym: " brefeldin A " NARROW [CHEBI:48080]
3)	synonym: " rapamycin " NARROW [CHEBI:9168]
4)	synonym: " latrunculin B " NARROW [CHEBI:49703]

**Comment by dianeoinglis** [comment]
I am ambivalent about the format "resistance phenotype." The observable is "growth on amphotericin B" which is an anti-fungal drug. The "resistance" term would certainly be appropriate as an APO synonym. 

Brefeldin A: "protein and vesicle transport inhibitor.  BFA is known to arrest the anterograde transport of proteins between the ER and Golgi apparatus by interfering with the action of ARF. It is a lactone antibiotic produced by fungal organisms such as Eupenicillium brefeldianum. Brefeldin A inhibits protein transport from the endoplasmic reticulum to the Golgi apparatus indirectly by preventing formation of COPI-mediated[2] transport vesicles. Brefeldin A was initially isolated as an anti-viral antibiotic[3] but is now primarily used in biological research to study protein transport.
BFA is used to test ability to grow on plates with BFA and in liquid media to test capsule formation as it inhibits secretion of capsule material.
https://en.wikipedia.org/wiki/Brefeldin_A
http://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.0030042
http://www.ncbi.nlm.nih.gov/pubmed/19450701

rapamycin (aka sirolimus): Rapamycin is often added to media on petri plates.
Sirolimus (INN/USAN), also known as rapamycin, is a macrolide (one of a group of drugs containing a macrolide ring) produced by the bacterium Streptomyces hygroscopicus. It is a common inhibitor of mTor as well as fungal Tors.
https://en.wikipedia.org/wiki/Sirolimus
http://www.ncbi.nlm.nih.gov/pubmed/10330150

latrunculin B:
An actin cytoskeleton inhibitor. The latrunculins are a family of natural products and toxins produced by certain sponges, including genus Latrunculia and Negombata, whence the name is derived. It binds actin monomers near the nucleotide binding cleft with 1:1 stoichiometry and prevents them from polymerizing. Administered in vivo, this effect results in disruption of the actin filaments of the cytoskeleton. This property has been used to great effect in the discovery of cadherin distribution regulation.
https://en.wikipedia.org/wiki/Latrunculin

Amphotericin B: phenotype is "antifungal drug resistance" and is usually tested on petri plates.
Amphotericin B is an antifungal drug often used intravenously for serious systemic fungal infections and is the only effective treatment for some fungal infections. It was originally extracted from Streptomyces nodosus, a filamentous bacterium. It is of the polyene class.

**Comment by dianeoinglis** [comment]
Another inhibitor of the macrolide type is bafilomycin A1 that has phenotypes in Cryptococcus.

https://en.wikipedia.org/wiki/Bafilomycin
The bafilomycins are a family of toxic macrolide antibiotic derived from Streptomyces griseus. These compounds all appear in the same fermentation and have quite similar biological activity. Bafilomycins are specific inhibitors of vacuolar-type H+-ATPase. The most used bafilomycin is bafilomycin A1. This is a useful tool as it can prevent the re-acidification of synaptic vesicles once they have undergone exocytosis. Bafilomycin has antibacterial, antifungal, antineoplastic, immunosuppressive activities.

Diane

**Comment by Achchuthan** [comment]
Can we add bafilomycin A1 as synonym as well please ?

synonym: " bafilomycin A1 " NARROW [CHEBI:22689]

**Comment by dsiegele** [comment]
Hi Diane,

You wrote: "I am ambivalent about the format "resistance phenotype." The observable is "growth on amphotericin B" which is an anti-fungal drug. The "resistance" term would certainly be appropriate as an APO synonym."

We decided to have OMP phenotype terms describe the inference made from a observable, rather than the observable itself, and to capture the observable with the ECO term and the environment field. Our reasoning for this is that otherwise you end up with multiple terms for a single phenotype that can be observed in multiple ways. For example, the ability to use lactose as a carbon and energy source (Lac+) could be based on growth on minimal medium containing lactose or it could be based on appearance on indicator medium, such as MacConkey Lactose medium where Lac+ cells form red colonies and Lac- cells form white colonies. 

Thinking about resistance and sensitivity phenotypes and -static vs. -cidal agents, I realize that implicit in the definition is that resistance means to be able to grow in the presence of the agent and sensitivity means no growth. I am thinking that we should make that explicit in the term definitions. What do you think?

**Comment by dsiegele** [comment]
Added requested synonyms: amphotericin B, brefeldin A, rapamycin, latrunculin B, bafilomycin A1. I will close this issue and open a new one for discussion of how to define resistance terms.

**Comment by dianeoinglis** [comment]
Hello Debby,

I am systematically browsing all the branches and want to comment on the way "OMP:0000274 ! antimicrobial agent resistance phenotype" includes a list of the types of antimicrobial agents as synonyms. For the antifungal agents, it is significant to differentiate the specific antifungal drug as there are differences in efficacy toward different fungal species or strains. Would you consider creating child terms for each drug as this format loses the antifungal-specific phenotypes that i have captured and causes difficulty if there are two phenotypes such as a strain has a "decreased resistance to voriconazole" and a "normal or increased resistance to fluconazole." The display of the phenotype would be more straightforward to identify at a glance without having to look up the synonyms,

Diane

**Comment by dsiegele** [comment]
To avoid a proliferation of terms for individual antimicrobial agents, our plan is to create terms for groups of antibiotics based on their structure and then put a CHEBI ID in the annotation extension field to identify the specific chemical that was tested. The identify of the organism being assayed would be in the strain information, but I think an identifier for the organism could also be entered in the annotation extension field.  

In our annotation system, the annotation would read OMP:0006052 decreased resistance to azole; AN_EXT CHEBI:10023 voriconazole.

I can see how this system would be awkward if you aren't using the OMP annotation system. I will bring this up for discussion at our next OMP call.

**Comment by dsiegele** [comment]
created a new issue #xx for discussion of this topic.
