### ISSUE TITLE
Cryptococcus Compounds Xref: azole resistance phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#150]
OMP:0006028 ! azole resistance phenotype

Xref
1)	synonym: " benomyl " NARROW [CHEBI:3015]
2)	synonym: " fluconazole " NARROW [CHEBI:46081]
3)	synonym: " itraconazole " NARROW [CHEBI:6076]
4)	synonym: " ketoconazole " NARROW [CHEBI:47519]
5)	synonym: " miconazole " NARROW [CHEBI:6923]
6)	synonym: " posaconazole " NARROW [CHEBI:64355]
7)	synonym: " thiabendazole " NARROW [CHEBI:45979]
8)	synonym: " voriconazole " NARROW [CHEBI:10023]

**Comment by dsiegele** [comment]
Synonyms added.
