### ISSUE TITLE
Need parent term for benzamide antibiotic

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#156]
I want to annotate that a strain is resistant to Chir-090 and it isn't under any of the terms already present.

**Comment by dsiegele** [comment]
PUBCHEM CID:11546620
Chemical Names:	CHIR-090; 728865-23-4; N-{(1s,2r)-2-Hydroxy-1-[(Hydroxyamino)carbonyl]propyl}-4-{[4-(Morpholin-4-Ylmethyl)phenyl]ethynyl}benzamide

![chir-090](https://cloud.githubusercontent.com/assets/12094502/16364352/bdf409ee-3baa-11e6-8321-167f580b33d3.jpg)
