### ISSUE TITLE
Need parent term for acriflavine

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#157]
The other name for acriflavine is acroflavinium chloride

**Comment by dsiegele** [comment]
Made following terms for resistance to an acridine:
OMP:0007365	acridine resistance phenotype
.....OMP:0007367 not resistant to an acridine
.....OMP:0007366 resistant to an acridine
.....OMP:0007368 altered resistance to an acridine
..........OMP:0007369 increased resistance to an acridine
..........OMP:0007370 decreased resistance to an acridine
...............OMP:0007371 abolished resistance to an acridine
