### ISSUE TITLE
Need a parent term for alkylating agent 

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#159]
I want to annotate a strain that is resistant to MMS, but the category for it does not exist yet.

**Comment by dsiegele** [comment]
Added parent term 'alkylating agent resistance phenotype,' but still need to make child terms for presence, absence, altered, etc.

**Comment by dsiegele** [comment]
Finished making child terms for alkylating agent resistance phenotype:
OMP:0007372	alkylating agent resistance phenotype
.....OMP:0007374 ! not resistant to alkylating agent
.....OMP:0007373 ! resistant to alkylating agent
.....OMP:0007375 ! altered resistance to alkylating agent
..........OMP:0007377 ! decreased resistance to alkylating agent
................OMP:0007378	abolished resistance to alkylating agent
..........OMP:0007376 ! increased resistance to alkylating agent
