### ISSUE TITLE
need a parent term for nucleoside antibiotic

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#160]
I'm annotating a strain that's resistant to Azidothymidine, and it isn't under any of the terms already present

**Comment by dsiegele** [comment]
Terms added to omp-edit.obo file. Added puromycin and azidothymidine as narrow synonyms. Changed/added OMP IDs in the OMPwiki for these antibiotics.

**Comment by dsiegele** [comment]
OMP:0007358	nucleoside resistance phenotype
OMP:0007359	resistant to a nucleoside
OMP:0007360	not resistant to a nucleoside
OMP:0007361	altered resistance to a nucleoside
.....OMP:0007362	Increased resistance to a nucleoside
.....OMP:0007363	decreased resistance to a nucleoside
..........OMP:0007364	abolished resistance to a nucleoside
