### ISSUE TITLE
Need a parent term for phenol

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#165]
I want to annotate a strain that is resistant to Triclosan, but I need the parent term for it

**Comment by Jguzman210** [comment]
terms are made. I will be waiting on Dr. Siegele's approval to place them on OMP

**Comment by dsiegele** [comment]
Possible terms to use for a branch containing phenol and benzene (issue #166)

CHEBI:33832 organic cyclic compound
def: Any organic molecule that consists of atoms connected in the form of a ring.

CHEBI:33659 organic aromatic compound (is_a organic cyclic compound)

**Comment by kylliechang** [comment]
We currently have a chemical, CHIR-090, a benzamide, which could also fall under the category of an organic aromatic compound.

**Comment by dsiegele** [comment]
I created OMP:0007474 organic cyclic compound resistance phenotype. 

Jesus, would you please make the child terms for organic cyclic compound resistance phenotype?

presence of 
absence of
altered
increased
decreased 
abolished

**Comment by dsiegele** [comment]
Added narrow synonyms to OMP:0007474:
triclosan resistance phenotype
phenol resistance phenotype
phenol red resistance phenotype
rose bengal resistance phenotype

**Comment by Jguzman210** [comment]
Done.
