### ISSUE TITLE
new resistant term

### ISSUE THREAD

**Issue by sandylabonte** [microbialphenotypes/OMP-ontology#167]
resistance to cycloheximide

**Comment by dsiegele** [comment]
I will ask Jesus to add a new branch to antimicrobial agent resistance phenotype and add cycloheximide as a narrow synonym.

organic heterocyclic compound resistance phenotype  based on CHEBI:24532.

**Comment by dsiegele** [comment]
Sorry, Jesus. I didn't explain it well.  Cycloheximide is an example of an antimicrobial agent that is a heterocyclic organic compound. The terms that need to be made will be for "heterocyclic organic compound".  I put an example on the google doc. 

Cycloheximide will be added as a narrow synonym to the parent term 'organic heterocyclic compound resistance phenotype."

**Comment by Jguzman210** [comment]
Ok! I'll fix them by tonight!
Thank You Dr. Siegele!

**Comment by Jguzman210** [comment]
Terms with OMP #s. 

OMP:0005274	organic heterocyclic compound resistance phenotype
OMP:0005275	altered organic heterocyclic compound resistance
OMP:0005276	decreased resistance to organic heterocyclic compound
OMP:0005277	abolished resistance to organic heterocyclic compound
OMP:0005278	increased resistance to organic heterocyclic compound
OMP:0005279	not resistant to organic heterocyclic compound
OMP:0005280	resistant to organic heterocyclic compound

Thank You for your patience!

**Comment by dsiegele** [comment]
Sandy, 

Cycloheximide is an organic heterocyclic antibiotic. If S. pombe "wild-type" is sensitive to cycloheximide, you would annotate the strain with 'OMP:0005279 not resistant to organic heterocyclic compound' and put the CHEBI accession for cycloheximide (see above) in the phenotype extension field. If it is a mutant strain that has become resistant to cycloheximide you would use 'OMP:0005278 increased resistance to organic heterocyclic compound' and put the CHEBI accession for cycloheximide in the annotation extension field.

Debby
