### ISSUE TITLE
NTR: lethality (of host) caused by microbes

### ISSUE THREAD

**Issue by dsiegele** [microbialphenotypes/OMP-ontology#169]
Diane Inglis requested OMP terms for pathogens that can infect and cause lethality in a host (typically eukaryotic host). Taxon information for the host that suffers lethality can be captured by entering a taxon ID or some other designator in the annotation extension field. In addition, she requested terms for lethality in specific, commonly used hosts, such as mice. 

Please review terms below and send feedback:

lethality phenotype (is_a microbe-host interaction phenotype) def:A microbe-host interaction phenotype related to the ability of a microbe to infect and cause death of a host.

presence of lethality (is_a lethality phenotype) def: A lethality phenotype where infection by a microbe can cause death of the host.

absence of lethality (is_a lethality phenotype) def: A lethality phenotype where infection by a microbe does not cause death of the host.

altered lethality (is_a lethality phenotype) def: A lethality phenotype where the ability of an infectious  microbe to cause death of the host is altered relative to a designated control.

increased lethality (is_a altered lethality) def: An altered lethality phenotype where the ability of an infectious microbe to cause death of the host is increased relative to a designated control.

decreased lethality (is_a altered lethality) def: An altered lethality phenotype where the ability of an infectious microbe to cause death of the host is decreased relative to a designated control.

abolished lethality (is_a decreased lethality) def: A decreased lethality phenotype where the ability of an infectious microbe to cause death of the host is abolished.

presence of lethality in mice (is_a presence of lethality) def: A presence of lethality phenotype where the host of the infection is a mouse (or mice) (Mus musculus).

presence of lethality in immunocompromised mice (Is_a presence of lethality) def: A presence of lethality phenotype where the host of the infection is immunocompromised mouse (or mice) (Mus musculus).

absence of lethality in mice (is_a absence of lethality) def: An absence of lethality phenotype where the host of the infection is a mouse (or mice) (Mus musculus).

absence of lethality in immunocompromised mice (is_a absence of lethality) def: An absence of lethality phenotype where the host of the infection is an immunocompromised mouse (or mice) (Mus musculus).

altered lethality in mice (is_a altered lethality): An altered lethality phenotype xxx

**Comment by dianeoinglis** [comment]
These terms seem pretty good to me.

Diane

**Comment by dsiegele** [comment]
Finished adding the requested lethality terms to OMP.

OMP:0007394	lethality phenotype

OMP:0007395	presence of lethality
OMP:0007443	presence of lethality in immunocompromised mice
OMP:0007442	presence of lethality in mice

OMP:0007396	absence of lethality
OMP:0007445	absence of lethality in immunocompromised mice
OMP:0007444	absence of lethality in mice

OMP:0007397	altered lethality
OMP:0007398	decreased lethality
OMP:0007399	abolished lethality
OMP:0007447	decreased lethality in immunocompromised mice
OMP:0007449	abolished lethality in immunocompromised mice
OMP:0007446	decreased lethality in mice
OMP:0007448	abolished lethality in mice
OMP:0007400	increased lethality
OMP:0007451	increased lethality in immunocompromised mice
OMP:0007450	increased lethality in mice

**Comment by dianeoinglis** [comment]
Hi Debby,

The term "altered lethality"is probably best removed/obsoleted. The qualifiers abolished, decreased and increased are the important terms and it is best if the terms with "altered" should not be an option for curation

Also, can these synonyms be added?
abolished lethality -> Syn: avirulent
increased lethality -> Syn: hypervirulent
decreased lethality -> Syn: hyporvirulent

Thanks!
Diane

**Comment by mchibucos** [comment]
Hi Diane,
We use 'altered phenotype' terms as umbrellas to group the 'increased', 'decreased', and 'abolished' process terms. This was a decision we made long ago within the OMP group (I don't recall if the discussion is documented in a linkable way, however - I'd have to check my notes from an early Texas meeting). So, to make those terms you suggest obsolete would actually be a non-minor decision - it would force us to revisit our major ontological design - which I'm thinking we wouldn't prefer to do at this time. That said, you are correct - people should not annotate with "altered" if there is a better choice. And there may typically be a better choice for many relative process-related terms, many of which could have increased/decreased/abolished as qualifiers... But for many terms pertaining to character states, such as "colony morphology", 'altered' might actually be the best choice, for example, 'OMP:0007160 ! altered colony morphology'. We spoke at one time about making a note about when to use/not use "altered terms"/umbrella terms. Maybe we need another issue to address this?
Marcus

**Comment by dianeoinglis** [comment]
Hi Marcus,

No major changes in policy are necessary. I would just like to discourage the use of the term by curators of pathogenesis phenotypes. My rationale is if the term does not exist, it can't be applied. Is there a way to note the term is a grouping term or other means of noting increased, decreased and abolished are the desirable term choices?

Thanks!
Diane
