### ISSUE TITLE
Need a parent term for a coumarin

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#174]
I'm annotating a strain that's resistant to Novobiocin, and the term for it does not already exist in the antimicrobial agent resistance phenotype.

**Comment by dsiegele** [comment]
Hi Kyllie!  

novobiocin is a coumarin which is a heterocyclic organic compound. Use one of the terms I copied into issue #176 and put the CHEBI ID for novobiocin (CHEBI:28368) in the annotation extension field.  

Debby
