### ISSUE TITLE
Need a parent term for phosphonic acid

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#175]
I'm annotating a strain that's resistant to glufosfomycin, and the term for it does not exist yet.

**Comment by dsiegele** [comment]
Nichols et al. used the abbreviation glufosfomycin for the combination of fosfomycin and glucose-6-phosphate. I'm not sure how we are going to capture combinations like this. We need to have a discussion with the rest of the OMP group.
