### ISSUE TITLE
Need a parent term for thiolactone

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#176]
I'm annotating a strain that's resistant to Thiolactomycine, and the term for tiolactone does not exist yet.

**Comment by dsiegele** [comment]
Thiolactomycin and thiolactones are heterocyclic organic compounds. I added both as narrow synonyms of heterocyclic organic compound resistance. You can choose from the terms below to make the annotations and put the PubChem accession for thiolactomycin (CID:445629) in the phenotype extension field. I didn't find a CHEBI accession for thiolactomycin. 

OMP:0005274 organic heterocyclic compound resistance phenotype
OMP:0005275 altered organic heterocyclic compound resistance
OMP:0005276 decreased resistance to organic heterocyclic compound
OMP:0005277 abolished resistance to organic heterocyclic compound
OMP:0005278 increased resistance to organic heterocyclic compound
OMP:0005279 not resistant to organic heterocyclic compound
OMP:0005280 resistant to organic heterocyclic compound
