### ISSUE TITLE
 Cryptococcus NTR: colonization of host and host tissue phenotypes

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#180]
Hello,

The ability of fungal cells to survive within a host can be measured but is the exact tissues may not be determined (or the fungal cells disseminate to many tissues).  Cryptococcus disseminates to the CNS and brain and causes meningitis. In this case, the route of infection may be intranasal (pulmonary) but the tissue examined for fungal cells is typically the brain or CNS fluid. In rabbits, the route of infection is a direct sub-lethal dose inoculated directly in the CNS. I would like a term for the tissue specific assays used for Cryptococcus.

Is there a reason that OMP:0007252 was formatted as "host colonization phenotype" as opposed to "colonization of a host phenotype?" 

Cryptococcus neoformans and C. grubii are opportunistic fungi and require an immunocompromised host for successful infections but C. gattii is considered a primary pathogen and infects immunocompetent hosts. 

Compare  "immunompromised host colonization phenotype "versus "colonization of immunocompromised host phenotype"

When the immune status of the host is specified, the format "colonization of immunocompromised host phenotype" seems preferable  than "immunocompromised host colonization phenotype" but the order verb-noun or noun-verb is more of a minor detail and not a major issue. 

These are the new terms I am requesting:
Altered, decreased, increased and abolished:
- colonization of host tissue phenotype
- colonization of  immunocompromised host tissue phenotype
- colonization of immunocompromised host tissue phenotype
- colonization of mouse tissue phenotype
- colonization of  immunocompromised mouse tissue phenotype
- colonization of rabbit tissue phenotype
- colonization of  immunocompromised rabbit tissue phenotype

Thank you!
Diane

**Comment by dsiegele** [comment]
Hi Diane,

Thank you! "colonization of a host phenotype" is much better than "host colonization phenotype."

**Comment by dsiegele** [comment]
Rename existing terms:
OMP:0007252	host colonization phenotype change to 'colonization of a host phenotype'
OMP:0007254	absence of host colonization change to 'absence of colonization of a host'
OMP:0007253	presence of host colonization change to 'presence of colonization of a host'
OMP:0007255	altered host colonization change to 'altered colonization of a host'
OMP:0007256	Increased host colonization change to 'increased colonization of a host'
OMP:0007257	decreased host colonization change to 'decreased colonization of a host'
OMP:0007258	abolished host colonization change to 'abolished colonization of a host'

You will need to tweak the definitions to match the new term names. 

New terms: will add these later :-)

**Comment by dianeoinglis** [comment]
Wonderful!!!

**Comment by Jguzman210** [comment]
Here are the new terms with matching OMP numbers

OMP:0007258	abolished colonization of a host
OMP:0005287	abolished colonization of host tissue
OMP:0005294	abolished colonization of immunocompromised host tissue
OMP:0005301	abolished colonization of mouse tissue
OMP:0005315	abolished colonization of rabbit tissue
OMP:0005308	abolished colonization of tissue in an immunocompromised mouse
OMP:0005322	abolished colonization of tissue in an immunocompromised rabbit
OMP:0007254	absence of colonization of a host
OMP:0005283	absence of colonization of host tissue
OMP:0005290	absence of colonization of immunocompromised host tissue
OMP:0005297	absence of colonization of mouse tissue
OMP:0005311	absence of colonization of rabbit tissue
OMP:0005304	absence of colonization of tissue in an immunocompromised mouse
OMP:0005318	absence of colonization of tissue in an immunocompromised rabbit
OMP:0007255	altered colonization of a host
OMP:0005284	altered colonization of host tissue
OMP:0005298	altered colonization of mouse tissue
OMP:0005312	altered colonization of rabbit tissue
OMP:0005291	altered colonization of tissue in an immunocompromised host
OMP:0005305	altered colonization of tissue in an immunocompromised mouse
OMP:0005319	altered colonization of tissue in an immunocompromised rabbit
OMP:0007252	colonization of a host phenotype
OMP:0005281	colonization of host tissue phenotype
OMP:0005295	colonization of mouse tissue
OMP:0005309	colonization of rabbit tissue phenotype
OMP:0005288	colonization of tissue in an immunocompromised host phenotype
OMP:0005302	colonization of tissue in an immunocompromised mouse phenotype
OMP:0005316	colonization of tissue in an immunocompromised rabbit phenotype
OMP:0007257	decreased colonization of a host
OMP:0005286	decreased colonization of host tissue
OMP:0005293	decreased colonization of immunocompromised host tissue
OMP:0005300	decreased colonization of mouse tissue
OMP:0005314	decreased colonization of rabbit tissue
OMP:0005307	decreased colonization of tissue in an immunocompromised mouse
OMP:0005321	decreased colonization of tissue in an immunocompromised rabbit
OMP:0007256	increased colonization of a host
OMP:0005285	increased colonization of host tissue
OMP:0005299	increased colonization of mouse tissue
OMP:0005313	increased colonization of rabbit tissue
OMP:0005292	increased colonization of tissue in an immunocompromised host
OMP:0005306	increased colonization of tissue in an immunocompromised mouse
OMP:0005320	increased colonization of tissue in an immunocompromised rabbit
OMP:0007253	presence of colonization of a host
OMP:0005282	presence of colonization of host tissue
OMP:0005296	presence of colonization of mouse tissue
OMP:0005310	presence of colonization of rabbit tissue
OMP:0005289	presence of colonization of tissue in an immunocompromised host
OMP:0005303	presence of colonization of tissue in an immunocompromised mouse
OMP:0005317	presence of colonization of tissue in an immunocompromised rabbit

-Thank you for your patience :+1:

**Comment by dianeoinglis** [comment]
Thank you so much! These are awesome. For just a bit more awesomeness, there are two more host-types to create terms for.. Non-vertebrates (or invertebrates and amoebae) have become popular model hosts for characterizing bacterial and fungal pathogens. The  terms for "invertebrate host" will list the exact host in the annotation extension as will the "amoeba host." One question about the extensions. I want the vocabulary of the extensions to be controlled and am wondering if this is something I create outside of the OMP or is there a way to list the allowable terms for the extensions? 

presence of lethality in invertebrate host
absence of lethality in invertebrate host
altered lethality in invertebrate host
increased lethality in invertebrate host
decreased lethality in invertebrate host
abolished lethality in invertebrate host

Extensions for invertebrate hosts:
B. mori (silkworm)
C. elegans (nematode)
D. melanogaster (fruit fly)
G. gallonella (wax moth)


presence of lethality in amoeba host
absencee of lethality in amoeba host
altered lethality in amoeba host
increased lethality in amoeba host
decreased lethality in amoeba host
abolished lethality in amoeba host

Extensions for amoeba hosts:
C. castellani (amoeba)
D. discoidium (slime-mold)


Thanks!
