### ISSUE TITLE
Need a parent term for epoxide

### ISSUE THREAD

**Issue by kylliechang** [microbialphenotypes/OMP-ontology#183]
I'm annotating a strain that has a decreased resistance to Cerulenin, which is an epoxide.

**Comment by dsiegele** [comment]
I made the following terms, but only wrote a definition for OMP:0007495 epoxide resistance phenotype.  Jesus, would you enter definitions for the other terms?  

Debby 

OMP:0007495	epoxide resistance phenotype 
     def: An antimicrobial resistance phenotype relating to resistance or sensitivity to an epoxide. An epoxide is any cyclic ether in which the oxygen atom forms part of a 3-membered ring.
OMP:0007497	not resistant to an epoxide
OMP:0007496	resistant to an epoxide
OMP:0007498	altered epoxide resistance
.....OMP:0007500 decreased resistance to an epoxide
..........OMP:0007501 abolished resistance to an epoxide
.....OMP:0007499 increased resistance to an epoxide

**Comment by Jguzman210** [comment]
Got it!
