### ISSUE TITLE
Cryptococcus NTR altered protein localization phenotype

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#186]
I would like to request the term 'protein localization phenotype' independent of the 'protein distribution phenotype'

'protein localization phenotype'
'altered protein localization phenotype'

Thank you,
Diane

**Comment by Jguzman210** [comment]
Hi Diane! Is there a difference between protein localization and protein distribution? 
I uploaded the distribution terms already 
OMP:0005335: absence of protein localization
OMP:0005333: altered protein localization
OMP:0005334: presence of protein localization
OMP:0005332: protein localization phenotype

- Thank you

**Comment by dianeoinglis** [comment]
This is a good question. The two terms do seem to overlap entirely but I think we should look at the GO for guidance. "Distribution" does strike me as implying a specific pattern "of localization." The usage in GO seems nearly identical.
