### ISSUE TITLE
NTR terms related to altered motility

### ISSUE THREAD

**Issue by KristenKC** [microbialphenotypes/OMP-ontology#191]
Please make terms for:

altered cell motility by swarming
altered cell motility by swimming

**Comment by dsiegele** [comment]
OMP:0005323 altered cell motility by swarming
 +def: "A cell motility by swarming phenotype where the frequency, rate, timing, or extent of swarming is altered relative to a designated control." [OMP:JG]

OMP:0005324 altered cell motility by swimming
+def: "A cell motility by swimming phenotype where the frequency, rate, timing, or extent of swimming is altered relative to a designated control." [OMP:JG]

**Comment by dsiegele** [comment]
I added terms for altered cell motility by gliding and altered cell motility by twitching. Added "presence of" to cell motility term names. Reviewed and edited is_a relationships within the branch.
