### ISSUE TITLE
NTR: cell lysis phenotypes

### ISSUE THREAD

**Issue by KristenKC** [microbialphenotypes/OMP-ontology#192]
Create a child term of OMP:0007308 (cell death phenotype) called cell lysis phenotype then an increased cell lysis child term.

**Comment by Jguzman210** [comment]
OMP:0005336	cell lysis phenotype
OMP:0005342	increased cell lysis

**Comment by KristenKC** [comment]
Also, could we make an absence of cell lysis term?
