### ISSUE TITLE
FungiDB NTR: ascospore morphology phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#197]
NTR
1.	ascospore morphology phenotype (is_a: OMP:0008000 ! spore morphology phenotype)
FAO cross-reference:
id: FAO:0000020
name: ascospore
def: "A thick walled spore that stores and protects one or more nuclei following sexual reproduction in an Ascomycete." [SGD:clt]
is_a: FAO:0000017 ! sexual spore
2.	altered ascospore morphology (is_a ascospore morphology phenotype)

**Comment by dsiegele** [comment]
New terms were made. Please close issue if the definitions are OK.  Thank you!

OMP:0007511	ascospore morphology phenotype
     def: A spore morphology phenotype that is related to the form and structure of an ascospore, which is a thick-walled spore that stores and protects one or more nuclei following sexual reproduction in an Ascomycete.
     Dbxref: FAO:0000020 ascospore; CL:0000607 ascospore

OMP:0007512	altered ascospore morphology
     def: An ascospore morphology phenotype in which the form and structure of an ascospore is altered relative to a designated control.

**Comment by Achchuthan** [comment]
Thanks a lot Debby for the new terms. The terms and definitions are great.
