### ISSUE TITLE
Term redirects-OMPwiki

### ISSUE THREAD

**Issue by sandyl27** [microbialphenotypes/OMP-ontology#223]
When I searched for nitrogen on OMP, these terms pulled up:

Category:OMP:0006005 ! nitrogen source utilization
Category:OMP:0006007 ! nitrogen requirement source
Category:OMP:0006013 ! nitrogen source requirement

however when you click them they actually redirect to other un related terms like Category:OMP:0006013 ! altered transposable element transposition phenotype

**Comment by dsiegele** [comment]
This is present in the omp-edit.obo code, so it appears to be a mistake in the wiki. Sandy and Jim will work on fixing it.

**Comment by dsiegele** [comment]
moved this issue to the OMPwiki tracker
