### ISSUE TITLE
A few cases of <new synonym> in OBO file

### ISSUE THREAD

**Issue by althonos** [microbialphenotypes/OMP-ontology#255]
Hi !

This one is not critical, but there are a few cases of incomplete synonym definitions (`synonym: "<new synonym>" RELATED []`) in the following frames:
- `OMP:0000087`
- `OMP:0000280`
- `OMP:0005059`
- `OMP:0006068`
- `OMP:0007813`
- `OMP:0007816`

**Comment by dsiegele** [comment]
I made the following corrections:
    OMP:0000087 - deleted "<new synonym>" RELATED []
    OMP:0000280 - deleted "<new synonym>" RELATED []
    OMP:0005059 - deleted "<new synonym>" RELATED []
    OMP:0006068 - deleted "<new synonym>" RELATED []
    OMP:0007813 - added term name for narrow synonym FYPO:0000740 normal cellular pigment accumulation
    OMP:0007816 - added term name for exact synonym FYPO:0000741 increased cellular pigment accumulation
