### ISSUE TITLE
Nitrogen utilization redirects to site-specific recombination

### ISSUE THREAD

**Issue by peterwu19881230** [microbialphenotypes/OMP-ontology#264]
https://microbialphenotypes.org/wiki/index.php?title=Category:OMP:0006005_!_nitrogen_source_utilization

**Comment by dsiegele** [comment]
Peter,

The phenotype term you want to use to annotate  OMP ST:74667 ! Virtual reference strain for Nichols RJ (2011) Cell 144, 143-156 is:
OMP:0007306 presence of inorganic nitrogen source utilization

**Comment by peterwu19881230** [comment]
got it
