### ISSUE TITLE
Cryptococcus 'cell size'

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#68]
Hi there,

An increased cell size was the only 'altered cell size' phenotype observed for Cryptococcus. No new term needed. APO cross-ref desired.

The APO cross-ref:  
id: APO:0000052
name: cell size

id: OMP:0000041
name: increased cell size
def: "An altered cell size phenotype where the volume of a cell or cells is increased relative to a designated control." [OMP:MCC]
is_a: OMP:0007083 ! altered cell size

Thank you!

Diane

**Comment by dsiegele** [comment]
Added APO:0000052 ! cell size as a XRef to the parent term OMP:0000074 ! cell size phenotype.

**Comment by dianeoinglis** [comment]
Great. Thank you!

Diane
