### ISSUE TITLE
Cryptococcus cell cycle progression

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#69]
This one should be easy.
term used in APO
cell cycle progression: delayed

Suggested OMP term:
delayed cell cycle progression

This phenotype would be a child term of:

id: OMP:0005136
name: altered cell cycle phenotype
def: "A cell cycle phenotype where progression of the cell cycle is altered relative to a designated control." [OMP:WAM]
comment: This term was created to organize terms beneath it in the ontology. We recommend that it not be used for annotation unless an appropriate child term cannot be found or requested.
is_a: OMP:0005115 ! cell cycle phenotype
is_a: OMP:0007085 ! altered phenotype

The APO cross-ref is:
id: APO:0000253
name: cell cycle progression
namespace: observable
alt_id: YPO:0000253
def: "Progression of cells through the mitotic cell cycle." [SGD:RSN]
subset: AspGD
subset: CGD
subset: Cryptococcus
subset: SGD
is_a: APO:0000072 ! mitotic cell cycle

Thanks! 

Diane

**Comment by Jguzman210** [comment]
delayed cell cycle progression::
An altered cell cycle phenotype where progression of the cell cycle is delayed relative to a designated control.

OMP:0005172

**Comment by dianeoinglis** [comment]
Can "cell cycle" have the synonym "cell division cycle?"
Thanks!
Diane

**Comment by dsiegele** [comment]
JGuzman added "cell division cycle" as synonym to OMP:0005115 cell cycle phenotype.
