### ISSUE TITLE
Cryptococcus cell shape phenotype terms

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#70]
Phenotype:
"cell shape: abnormal"

Suggested OMP term:

id: OMP:0007101
name: altered cell shape
def: "A cell shape phenotype where the shape of a cell is altered relative to a designated control." [OMP:DAS]
is_a: OMP:0000073 ! cell shape phenotype
is_a: OMP:0007103 ! altered cell morphology
intersection_of: OMP:0000073 ! cell shape phenotype
intersection_of: has_quality OMP:0007189 ! altered_relative_to

OR

id: OMP:0007103
name: altered cell morphology
def: "A cell morphology phenotype that is altered relative to a designated control." [OMP:DAS]
is_a: OMP:0000071 ! cell morphology phenotype
is_a: OMP:0007085 ! altered phenotype
intersection_of: OMP:0000071 ! cell morphology phenotype
intersection_of: has_quality OMP:0007189 ! altered_relative_to

The APO cross-refs are:
id: APO:0000051
name: cell shape
namespace: observable
alt_id: YPO:0000051
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000050 ! cellular morphology

id: APO:0000002
name: abnormal
namespace: qualifier
alt_id: YPO:0000002
def: "The observed phenotype is detectably different from that in the wild type." [SGD:curators]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000001 ! qualifier

**Comment by dsiegele** [comment]
I added APO:0000051 ! cell shape as a Xref to both OMP:0000073 ! cell shape phenotype and OMP:0007101 altered cell shape.

Need to discuss with rest of group if and how to reference APO:0000002 ! abnormal.

**Comment by dianeoinglis** [comment]
Hi Debbie,

The qualifier "abnormal" is used a lot with APO terms but "altered cell shape" or better yet, "altered cell morphology" seems to apply just as well as the original "abnormal." I am happy to use 'altered' and call it done. Other phenotypes may be impacted by a change from abnormal to altered but this is not an issue from my end.

Thanks!
Diane
