### ISSUE TITLE
Cyptococcus colony appearance phenotypes

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#71]
Recorded Cryptococcus phenotype:
"colony appearance: abnormal"

APO cross-ref:
id: APO:0000060
name: colony appearance
namespace: observable
alt_id: YPO:0000060
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000158 ! culture appearance
id: APO:0000002
name: abnormal
namespace: qualifier
alt_id: YPO:0000002
def: "The observed phenotype is detectably different from that in the wild type." [SGD:curators]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000001 ! qualifier

The OMP terms listed below seem to be appropriate equivalents to the APO term recorded.

PHENOTYPES
1) colony appearance: abnormal
1) detail: mutant colonies appear dull instead of typical shiny surface when grown on solid medium

existing OMP: 
id: OMP:0000139
name: dull colony sheen
def: "A colony form phenotype characterized by a dull luster on the surface." [OMP:JCH]
synonym: "matte" RELATED []
synonym: "rough" RELATED []
xref: SNOMED:P3-513150
is_a: OMP:0000106 ! colony sheen phenotype

2) colony appearance: abnormal
2) detail: colonies have a dry appearance when grown on YPD plates for 3 days at 30 degrees C
3) colony appearance: abnormal
3) detail: dry, dull colony appearance, not as bright white as wild-type

Possible OMP equivalent term for 2 and 3:
id: OMP:0000236
name: dry colony consistency
def: "A colony consistency phenotype where a colony or colonies have a brittle or powdery consistency." [ISBN:1555810489, OMP:WAM]
synonym: "friable colony" EXACT []
xref: SNOMEDCT:87916001 "Bacterial colony consistency, friable"
is_a: OMP:0000229 ! colony consistency phenotype

4) colony appearance 
4) detail: colonies appear wet and "running" 

possible OMP equivalent terms:
id: OMP:0000109
name: mucoid colony
def: "A colony surface phenotype that is characterized by a surface with a slimy or gummy appearance." [ISBN:1555810489, OMP:WAM]
synonym: "viscous colony texture" RELATED [OMP:WAM]
is_a: OMP:0000210 ! colony surface phenotype

OR

id: OMP:0007126
name: viscous colony consistency
def: "A colony consistency phenotype where a colony or colonies have a sticky or gummy consistency." [ISBN:1555810489, OMP:WAM]
xref: SNOMEDCT:16601003 "Bacterial colony consistency, viscous"
is_a: OMP:0000229 ! colony consistency phenotype

Comment: 'mucoid colony' seems like it is also a colony consistency phenotype.

If the above OMP terms are acceptable for the Cryptococcus phenotypes, then the OMP terms will be applied.

**Comment by dsiegele** [comment]
-Xef to APO:0000060 colony appearance was added

- OMP:0007160 altered colony morphology could be used to annotate mutants with abnormal colony appearance

-
