### ISSUE TITLE
Cryptococcus colony stain/color phenotype

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#72]
APO recorded APO phenotype is "colony color: abnormal"

This phenotype is forced into a colony color term for lack of a better APO term. The detail is:
"mutants lose positive staining by diazonium blue B (DBB), a stain that can distinguish basidomycete yeast from ascomycetes." A more specific term would be nice.

Possible NTR:
'abolished diazonium blue B colony stain'
OR
'abolished diazonium blue B basidiomycete stain'

APO cross-refs:
id: APO:0000061
name: colony color
namespace: observable
alt_id: YPO:0000061
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000060 ! colony appearance

id: APO:0000002
name: abnormal
namespace: qualifier
alt_id: YPO:0000002
def: "The observed phenotype is detectably different from that in the wild type." [SGD:curators]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000001 ! qualifier

id: APO:0000002
name: abnormal
namespace: qualifier
alt_id: YPO:0000002
def: "The observed phenotype is detectably different from that in the wild type." [SGD:curators]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000001 ! qualifier

**Comment by dsiegele** [comment]
Diane, 
I created following terms for diazonium blue b staining:
OMP:0007294 diazonium blue B staining phenotype
.....OMP:0007295 presence of diazonium blue B staining
.....OMP:0007296 absence of diazonium blue B staining
.....OMP:0007297 altered diazonium blue B staining
..........OMP:0007301 decreased diazonium blue B staining
...............OMP:0007303 abolished diazonium blue B staining
..........OMP:0007302 increased diazonium blue B staining

Please check the definitions and send feedback.

I added a XRef to APO:0000061 ! colony color to the top term (OMP:0007294).

I cited the following references:
Hagler and Ahearn (1981) Int J Syst Evol Microbiol 31:204-208.  doi:10.1099/00207713-31-2-204
Van Der Walt and Hopsu-Havu (1976) Antonie van Leeuwenhoek 42:157-173.  PMID:60081

Please let me know if there is a more commonly used reference that I should use instead.

thanks,

Debby

**Comment by dianeoinglis** [comment]
The references look fine.
Diane
