### ISSUE TITLE
Comments on conversion of APO-based terms to OMP

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#73]
The Stanford DBs, SGD, CGD and AspGD, completely revolve around the APO. The phenotypes go hand in hand with several "details" displayed on the webpages and with the downloadable files. These additional details will be lost if not incorporated into the new phenotype terms. It would be nice to preserve as much detail as possible but I do have the option of including any details in a supplemental table to the manuscript so it's a matter of how you all want the OMP terms to develop.

Examples from Stanford DBs:
http://www.yeastgenome.org/cgi-bin/search/luceneQS.fpl?query=colony
http://www.candidagenome.org/cgi-bin/phenotype/phenotype.pl?observable=colony%20appearance&organism=C_albicans_SC5314
http://www.aspergillusgenome.org/cgi-bin/phenotype/phenotype.pl?observable=colony%20appearance&organism=A_nidulans_FGSC_A4

Thanks! 
Diane

**Comment by dianeoinglis** [comment]
Also, for Cryptococcus, some of the "normal" phenotypes were recorded. These were mostly 'capsule formation' and 'virulence.' The capsule is an absolute virulence determinant. Acapsular strains are universally avirulent so the status of capsule formation is an important detail that we thought should be captured. A term for a "present" or "normal" phenotype would be ideal.

Diane

**Comment by dsiegele** [comment]
Additional information, such as experiment type, mutant information, and phenotype details, can be associated with terms from OMP using our annotation system (microbialphenotypes.org). 

Here's an example for a mutant strain: http://microbialphenotypes.org/wiki/index.php/OMP_ST:773_!_Strain:Escherichia_coli_K-12_AW518

The annotations of mutant phenotypes are linked to the annotation of the appropriate parent strain.  For example, in the first row, OMP_ST:773 is annotated with the phenotype term OMP:0007005 decreased negative chemotaxis.  The information in the fifth column (Relative phenotype information) shows that the comparison is with a strain of a different genotype and provides a link to the parent strain. If you click the link and scroll down to the row labeled OMP_AN:403, you'll see the parent strain OMP_ST:772 is annotated with the phenotype term OMP:0000053 presence of negative chemotaxis. 

Details about a particular phenotype can be entered as free text in the last column (Notes).

We're working with ECO to develop terms for experimental assays that are not yet included in the evidence code ontology.

In the near future, we plan to implement pages that will automatically collect and display all the phenotypes associated with a particular gene.

**Comment by dianeoinglis** [comment]
Perfect. Thank you. 
Dianr

**Comment by dianeoinglis** [comment]
Perfect. Thank you. 
Diane
