### ISSUE TITLE
Cryptococcus cell death by apoptosis

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#75]
APO-based phenotype term:
"apoptosis: decreased"

OMP NTR:
"decreased apoptosis"
is_a "cell death phenotype"

APO cross-refs:
id: APO:0000155
name: apoptosis
namespace: observable
alt_id: YPO:0000155
def: "An energy-dependent, programmed form of cell death that is characterized by phenotypic markers such as increased levels of reactive oxygen species (often detected via DHE staining), externalization of phosphatidylserine (measured by annexin V staining), and DNA fragmentation (detected using the TUNEL assay). Other processes observed during apoptosis include chromosome condensation and breakdown of mitochondria, including loss of membrane potential and release of cytochrome c. Cells undergoing apoptosis do not lose plasma membrane integrity (measured by propidium iodide staining) until late in the process." [PMID:15556039, PMID:18452540, PMID:18500447, PMID:18782613, PMID:19416362, SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000312 ! cell death

id: APO:0000312
name: cell death
namespace: observable
def: "The cessation of the life of an individual cell." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000066 ! cellular processes

**Comment by dsiegele** [comment]
Proposed branch structure:
biological process phenotype
.....cell death phenotype (Xref APO:0000312)
..........apoptosis phenotype (Xref APO:0000155)

**Comment by dianeoinglis** [comment]
Yes. Fewer TUNEL positive cells are observed so fewer cells undergo apoptosis..
PMID:22114551

Diane

**Comment by dianeoinglis** [comment]
Can the term 'rate' be added to the following apoptosis phenotypes?

OMP:0007313 ! decreased apoptosis -> decreased 'rate of' apoptosis
OMP:0007314 ! increased apoptosis -> increased 'rate of' apoptosis

Thank you,
Diane

**Comment by dianeoinglis** [comment]
Pending modification:

OMP:0007313 ! decreased apoptosis -> "decreased 'rate of' apoptosis" OR "decreased apoptosis rate"
OMP:0007314 ! increased apoptosis -> "increased 'rate of' apoptosis" OR "increased apoptosis rate"

Thanks.
