### ISSUE TITLE
Cryptococcus capsule formation phenotypes

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#76]
"Capsule formation" is an "anatomical structure formation" term but it's not clear whether capsule is a true anatomical structure. This is probably debatable. "Capsule" does not appear to be in the Fungal Gross Anantomy (FAO). It seems best to apply the existing "capsule" phenotype terms in OMP as is. Perhaps some added definition would be helpful.

The phenotypes captured for Cryptococcus are:
capsule formation: absent
capsule formation: decreased
capsule formation: increased
capsule formation: normal
capsule formation: abnormal (I am not sure about this term applied to detail: 'altered polysaccharide composition,' 'enlarged capsules with altered architecture,' 'enlarged capsule,' and 'asymetric, partially detached capsule.")

APO cross-ref:
id: APO:0000331
name: capsule formation
namespace: observable
def: "The formation of a coating of extracellular polysaccharide material, as in fungi such a Cryptococcus." [CryptoGD:doi]
subset: CryptoGD
is_a: APO:0000291 ! formation of anatomical structure

APO term "capsule formation: absent" equivalent to OMP:0006102 or OMP:0000211 (consider merging OMP terms)
id: OMP:0006102
name: abolished capsule formation
def: "A decreased amount of capsule phenotype where capsule is abolished." [OMP:JCH]
is_a: OMP:0000050 ! decreased amount of capsule
OR
id: OMP:0000211
name: absence of capsule
def: "A capsule phenotype where a cell or cells lack capsule." [OMP:DAS]
is_a: OMP:0000203 ! capsule phenotype

APO term "capsule formation: increased" (also "enlarged capsule") equivalent to OMP:0000036
id: OMP:0000036
name: increased amount of capsule
def: "An altered capsule phenotype where the amount of capsule is increased relative to a designated control." [OMP:DAS]
is_a: OMP:0007133 ! altered capsule phenotype

APO term "capsule formation: decreased" equivalent to
APO term "capsule formation: normal"
id: OMP:0000204
name: presence of capsule
def: "A capsule phenotype where a cell or cells have capsule." [OMP:DAS]
comment: When present, the capsule layer lies outside the cell wall and/or outer membrane.
synonym: "glycocalyx" RELATED [OMP:DAS]
synonym: "slime layer" RELATED [OMP:DAS]
is_a: OMP:0000203 ! capsule phenotype

APO term: "capsule formation: abnormal"
id: OMP:0007133
name: altered capsule phenotype
def: "A capsule phenotype where the capsule layer is altered relative to a designated control." [OMP:DAS]
is_a: OMP:0000203 ! capsule phenotype

APO term "capsule formation: abnormal with detail "enlarged capsules with altered architecture" may require 2 terms: 
1) id: OMP:0007133
name: altered capsule phenotype
2) id: OMP:0000036
name: increased amount of capsule

APO term "capsule formation: abnormal" with detail "asymetric, partially detached capsule" can get the term OMP:0007133 "altered capsule phenotype"

APO term "capsule formation: abnormal" with detail "'altered polysaccharide composition"
Possible NTR: "altered capsule composition"

These take care of capsule phenotypes.

Thanks!
Diane

**Comment by dsiegele** [comment]
i) added xref to APO:0000331 to OMP:0000203 ! capsule phenotype

ii) "APO term "capsule formation: absent" equivalent to OMP:0006102 or OMP:0000211 (consider merging OMP terms)"
     OMP contains these two separate terms in order to annotate two distinct classes of phenotypes: independent and dependent phenotypes. Independent phenotypes provide information about an organism with a particular genotype in a particular environment without reference to any other genotype or environment. OMP:0000211 'absence of capsule' is an example of an independent phenotype.
     Dependent phenotypes capture a relative difference observed when comparing two separate genotypes or growth conditions. OMP:0000050 'decreased amount of capsule' is a dependent phenotype, which would be used when describing the phenotype of a mutant relative to its parent or when describing the phenotypes seen in two different growth conditions. OMP:0006102 'abolished capsule formation' is also a dependent phenotype.

**Comment by dianeoinglis** [comment]
Hi Debbie,

If I'm understanding correctly, OMP:0000211 absence of capsule is not a "mutant" phenotype per se but a phenotypic trait of the organism. So for Cryptococcus, the following are the preferred terms:

OMP:0006102 'abolished capsule formation'
OMP:0000036 'increased amount of capsule'
OMP:0000050 'decreased amount of capsule'
OMP:0007133 'altered capsule phenotype' (for "abnormal")
OMP:0000204 'presence of capsule' (when there is no phenotype = "normal")

Thank you!
Diane
