### ISSUE TITLE
Cryptococcus NTR phosphatase activity

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#78]
NTR

decreased phosphatase activity

**Comment by Jguzman210** [comment]
Hi here are the phosphatase terms!

Phosphatase activity:
	An enzymatic activity phenotype that relates to the presence or absence of 	
Phosphatase, an enzyme that acts to modulate protein activity in cells. Phosphatase acts by removing phosphate groups off of active proteins making them enzymatically inactive. 
 OMP:0005160


Absence of Phosphatase activity
A Phosphatase phenotype where an organism doesn’t exhibit Phosphatase activity.

OMP:0005161


Altered Phosphatase activity
A Phosphatase phenotype where Phosphatase activity is altered relative to a designated control.
OMP:0005162


Decreased Phosphatase activity 
	A Phosphatase activity phenotype where Phosphatase activity is decreased relative to a designated control. 

OMP:0005163 


Increased Phosphatase activity
	An altered Phosphatase activity phenotype where Phosphatase activity is increased relative to a designated control. 

OMP:0005164


Presence of Phosphatase activity
A Phosphatase phenotype where an organism exhibits Phosphatase activity. 

OMP:0005165

**Comment by dianeoinglis** [comment]
Ok. Thanks!

Diane
