### ISSUE TITLE
Cryptococcus NTR phospholipase activity

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#79]
NTR

decreased phospholipase activity

**Comment by dsiegele** [comment]
Jesus created phospholipase activity phenotype terms: 
OMP:0005000 ! phospholipase activity phenotype
....OMP:0005019 ! absence of phospholipase activity
.....OMP:0005026 ! presence of phospholipase activity
.....OMP:0005028 ! altered phospholipase activity
..........OMP:0005062 ! increased phospholipase activity
..........OMP:0005063 ! decreased phospholipase activity
...............OMP:0005110 ! abolished phospholipase activity

DAS created connections between: abolished phospholipase activity and absence of phospholipase activity; altered phospholipase activity and altered enzymatic activity.

**Comment by dianeoinglis** [comment]
Thank you. Looks great!

Diane
