### ISSUE TITLE
Cryptococcus NTR protein kinase A activity

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#80]
NTR

decreased protein kinase A activity

**Comment by Jguzman210** [comment]
Protein Kinase A terms have been completed

protein kinase a activity:
	An enzymatic activity phenotype that relates to the presence or absence of 	
protein kinase a, an enzyme that belongs to the kinase AGC group. Protein kinase a acts by phosphorylating a wide array of enzymes, ion channels, chromosomal proteins, and transcription factors.

OMP:0005154


Absence of Protein kinase a activity
A protein kinase a phenotype where an organism doesn’t exhibit protein kinase a activity.

OMP:0005155


Altered Protein kinase a activity
A protein kinase a phenotype where protein kinase a activity is altered relative to a designated control.

OMP:0005156


Decreased Protein kinase a activity 
	A protein kinase a activity phenotype where protein kinase a activity is decreased relative to a designated control. 

OMP:0005157


Increased Protein kinase a activity
	An altered protein kinase a activity phenotype where protein kinase a activity 	is increased relative to a designated control.

OMP:0005158

Presence of Protein kinase a activity
A protein kinase a phenotype where an organism exhibits protein kinase a activity. 

OMP:0005159

**Comment by dianeoinglis** [comment]
Great. One detail is the "a" is typically capitalized:
Protein kinase A

Diane
