### ISSUE TITLE
Cryptococcus NTR superoxide dismutase activity

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#81]
NTR

decreased superoxide dismutase activity

**Comment by dianeoinglis** [comment]
Hello Jesus,

I cannot find the term ID for this one. Please help!

Thank you,
Diane

**Comment by dsiegele** [comment]
Hi Diane,

Here are the terms. Did you look for them on the wiki? They aren't showing up on the OMPwiki for some reason, but are in the omp.obo file. Jim will try to figure out what the problem with the wiki is.

Debby 

id: OMP:0005166
name: superoxide dismutase activity:
def: "An enzymatic activity phenotype that relates to the presence or absence of  superoxide dismutase, an enzyme that catalyzes the reaction:  2 superoxide + 2 H+ = O2 + hydrogen peroxide." [OMP:JG]
comment: This term was created to organize terms beneath it in the ontology. We recommend that it not be used for annotation unless an appropriate child term cannot be found or requested.
xref: GO:0004784 "superoxide dismutase activity"
is_a: OMP:0000221 ! enzymatic activity phenotype

id: OMP:0005167
name: absence of superoxide dismutase activity
def: "A superoxide dismutase phenotype where an organism does not exhibit superoxide dismutase activity." [OMP:JG]
is_a: OMP:0005166 ! superoxide dismutase activity:

id: OMP:0005171
name: presence of superoxide dismutase activity
def: "A superoxide dismutase phenotype where an organism exhibits superoxide dismutase activity." [OMP:JG]
is_a: OMP:0005166 ! superoxide dismutase activity:

id: OMP:0005168
name: altered superoxide dismutase activity
def: "A superoxide dismutase phenotype where superoxide dismutase activity is altered relative to a designated control." [OMP:JG]
is_a: OMP:0005130 ! altered enzymatic activity
is_a: OMP:0005166 ! superoxide dismutase activity:

id: OMP:0005169
name: decreased superoxide dismutase activity
def: "A superoxide dismutase activity phenotype where superoxide dismutase activity is decreased relative to a designated control." [OMP:JG]
is_a: OMP:0005168 ! altered superoxide dismutase activity
intersection_of: OMP:0005168 ! altered superoxide dismutase activity
intersection_of: has_quality PATO:0002302 ! decreased process quality
relationship: has_quality PATO:0002302 ! decreased process quality

id: OMP:0005170
name: increased superoxide dismutase activity
def: "An altered superoxide dismutase activity phenotype where superoxide dismutase activity is increased relative to a designated control." [OMP:JG]
is_a: OMP:0005168 ! altered superoxide dismutase activity
intersection_of: OMP:0005168 ! altered superoxide dismutase activity
intersection_of: has_quality PATO:0002304 ! increased process quality
relationship: has_quality PATO:0002304 ! increased process quality

**Comment by dianeoinglis** [comment]
Hi Debby,

I have been having trouble finding terms on the wiki. I did not go straight to the omp.obo file but will for future searches.

Thank you,

Diane

**Comment by jimhu-tamu** [comment]
I'm not sure what's going on with the wiki loading, but now that I have a list, I will debug.

Jim

On May 8, 2016, at 3:56 PM, Diane O Inglis <notifications@github.com> wrote:

> Hi Debby,
> 
> I have been having trouble finding terms on the wiki. I did not go straight to the omp.obo file but will for future searches.
> 
> Thank you,
> 
> Diane
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

=====================================
Jim Hu
Professor
Dept. of Biochemistry and Biophysics
2128 TAMU
Texas A&M Univ.
College Station, TX 77843-2128
979-862-4054
