### ISSUE TITLE
Cryptococcus NTR ferric reductase activity

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#82]
NTR

increased ferric reductase activity

**Comment by Jguzman210** [comment]
Hi! here are the ferric reductase terms

Ferric reductase activity:
	An enzymatic activity phenotype that relates to the presence or absence of 	
Ferric reductase, a class of flavin reductases. Ferric reducatases act on ferric iron to reduce it by using NADH or NADPH as the electron donor. 

OMP:0005148


Absence of ferric reductase activity:
A ferric reductase phenotype where an organism doesn’t exhibit ferric reductase activity.

OMP:0005149


Altered ferric reductase activity:
A ferric reductase phenotype where ferric reductase activity is altered relative to a designated control.

OMP:0005150


Decreased ferric reductase activity 
	An altered ferric reductase activity phenotype where ferric reductase activity 	is decreased relative to a designated control. 

OMP:0005151


Increased ferric reductase activity:
	An altered ferric reductase activity phenotype where ferric reductase activity 	is increased relative to a designated control.

OMP:0005152

Presence of ferric reductase activity:
A ferric reductase phenotype where an organism exhibits ferric reducatse activity. 

OMP:0005153

**Comment by dianeoinglis** [comment]
Fabulous! Thank you!

Please excuse typos on any of these Crytococcus term requests. My laptop is still "iPhone" and text is not the same!

Diane
