### ISSUE TITLE
Cryptococcus NTR: vacuolar morphology phenotype

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#83]
NTR

1) vacuolar morphology phenotype

2) altered vacuolar morphology (is_a vacuolar morphology phenotype)

**Comment by Jguzman210** [comment]
I made the following terms : 
vacuolar morphology phenotype  OMP:0005144
    altered vacuolar morphology OMP:0005145
               decreased vacuolar size  OMP:0005146
               increased vacuolar size   OMP:0005147

**Comment by dianeoinglis** [comment]
Excellent!
Thanks,
Diane
