### ISSUE TITLE
Cryptococcus request for cross-references (Xref)

### ISSUE THREAD

**Issue by dsiegele** [microbialphenotypes/OMP-ontology#86]
From issue #67, Diane Inglis requested:
_cross-ref to matching APO terms
_cross-ref to FAO (Fungal Gross Anatomy Ontology) terms for 'anatomical structure' formation phenotypes

https://bioportal.bioontology.org/ontologies/FAO  downloaded onto OMP_shared/External_ontologies

**Comment by Jguzman210** [comment]
xref OMP 0000094 and 0008000 with FAO 0000019
