### ISSUE TITLE
Cryptococcus NTR: acid phosphatase activity phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#88]
Hi Debbie,

Can I request new phenotype terms for acid phosphatase activity please?

NTR
1) acid phosphatase activity phenotype
xref: GO:0003993 "acid phosphatase activity"
is_a: OMP:0000221 ! enzymatic activity phenotype
2) altered acid phosphatase activity (is_a acid phosphatase activity phenotype)
3) increased acid phosphatase activity (is_a altered acid phosphatase activity)
4) decreased acid phosphatase activity (is_a altered acid phosphatase activity)
5) abolished acid phosphatase activity (is_a decreased acid phosphatase activity)

Thanks & best wishes,
Achchuthan

**Comment by Jguzman210** [comment]
OMP numbers for the these terms are as follows:
Acid phosphatase activity phenotype- OMP:0005173
absence of acid  phosphatase activity - OMP:0005175
Altered activity - OMP:0005176
abolished activity - OMP:0005178
decreased activity - OMP:0005177
increased activity - OMP:0005179
presence of acid phosphatase - OMP:0005174

Sorry for the delay

**Comment by Achchuthan** [comment]
Dear Jesus & Debbie,

Thanks a lot for the help. No worries.

Best wishes,
Achchuthan
