### ISSUE TITLE
Cryptococcus NTR: adhesion phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#90]
NTR
1)	Adhesion phenotype
is_a: OMP:0000197 ! microbe-host interaction phenotype
APO cross-refs:
id: APO:0000288
name: adhesion
namespace: observable
def: "Adherence to a substrate in the environment or in a host." [AspGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000287 ! interaction with host/environment
2)	altered adhesion (is_a adhesion phenotype)
3)	adhesion to host tissue phenotype
is_a: adhesion phenotype
is_a: OMP:0000197 ! microbe-host interaction phenotype
4) altered adhesion to host tissue (is_a adhesion to host tissue phenotype)
5) increased adhesion to host tissue (is_a altered adhesion to host tissue)
6) decreased adhesion to host tissue (is_a altered adhesion to host tissue)
7) abolished adhesion to host tissue (is_a decreased adhesion to host tissue)

**Comment by dianeoinglis** [comment]
There is only one phenotype with this annotation for Cryptococcus and it is a "adhesion to host tissue" phenotype. I'd like to specify that it is a "host interaction."

PMID: 16487740

Thank you,
Diane

**Comment by dianeoinglis** [comment]
I guess "adhesion phenotype" should be the parent term and "adhesion to substrate" will potentially be another child/sibling term.

Diane

**Comment by Achchuthan** [comment]
I have added the parent term - microbe-host interaction, adhesion phenotype and its child term - adhesion to host tissue.

**Comment by dsiegele** [comment]
Here are the terms we're planning to make:

Child of biological process phenotype:
.....adhesion phenotype: A biological process phenotype that relates to the ability of a microbe to attach to a substrate in the environment or in a host, either directly or indirectly.
..........DBxref: APO:0000288 adhesion 	
		
Child of adhesion phenotype:
.....adhesion to host phenotype: An adhesion phenotype that relates to the ability of a microbe to attach to a host via adhesion molecules, general stickiness, etc., either directly or indirectly. The host is defined as the larger of the organisms involved in a symbiotic relationship.
..........DBxref: GO:0044406 adhesion to host

Children of adhesion to host phenotype:
.....absence of adhesion to host: An adhesion to host phenotype where a microbe lacks the ability to attach to a host.

.....presence of adhesion to host: An adhesion to host phenotype where a microbe has the ability to attach to a host.

.....altered adhesion to host: An adhesion to host phenotype where attachment of a microbe to a host is altered relative to a designated control.

Children of altered adhesion to host:
.....decreased adhesion to host: An altered adhesion to host phenotype where attachment of a microbe to a host is decreased relative to a designated control.
..........Child of decreased adhesion to host: abolished adhesion to host: A decreased adhesion to host phenotype where attachment of a microbe to a host is abolished.

.....increased adhesion to host: An altered adhesion to host phenotype where attachment of a microbe to a host is increased relative to a designated control.


I'm trying to figure out what PATO quality terms to use for decreased/increased adhesion. Can you send a reference that describes the assay used to measure adherence?

Debby

**Comment by Achchuthan** [comment]
Hi Debby,

Here is the reference for adhesion phenotype in Cryptococcus neoformans - PubMed ID: 16487740

http://www.sciencedirect.com/science/article/pii/S1286457905003989

Thanks,
Achchuthan

**Comment by dsiegele** [comment]
We've altered the definition for the altered adhesion to host phenotypes to: An adhesion to host phenotype where the frequency, rate, or extent of attachment of a microbe to a host is altered relative to a designated control.

We think this wording will cover a range of adhesion assays. If more specific terms are needed, we can add them in the future.

**Comment by Jguzman210** [comment]
Terms with OMP numbers

1) Adhesion phenotype OMP:0005205
2) altered adhesion (is_a adhesion phenotype) OMP:0005215
3) adhesion to host tissue phenotype OMP:0005206
4) altered adhesion to host (is_a adhesion to host tissue phenotype) OMP:0005209
5) increased adhesion to host (is_a altered adhesion to host tissue) OMP:0005212
6) decreased adhesion to host  (is_a altered adhesion to host tissue) OMP:0005210
7) abolished adhesion to host (is_a decreased adhesion to host tissue  OMP:0005211
