### ISSUE TITLE
Cryptococcus NTR: alpha-1,3-mannosyltransferase activity phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#91]
NTR
1) alpha-1,3-mannosyltransferase activity phenotype
is_a: OMP:0000221 ! enzymatic activity phenotype
2) altered alpha-1,3-mannosyltransferase activity (is_a alpha-1,3-mannosyltransferase activity phenotype)
3) increased alpha-1,3-mannosyltransferase activity (is_a altered alpha-1,3-mannosyltransferase activity)
4) decreased alpha-1,3-mannosyltransferase activity (is_a altered alpha-1,3-mannosyltransferase activity)
5) abolished alpha-1,3-mannosyltransferase activity (is_a decreased alpha-1,3-mannosyltransferase activity)

**Comment by dianeoinglis** [comment]
"abolished alpha-1,3-mannosyltransferase activity" is what is needed. We are not likely to need increased or decreased for this term as biochemistry is limited in Cryptococcus in favor of virulence and virulence trait assays.

Diane

**Comment by Jguzman210** [comment]
Terms with OMP #
1) alpha-1,3-mannosyltransferase activity phenotype OMP:0005198
2) altered alpha-1,3-mannosyltransferase activity OMP:0005201
3) increased alpha-1,3-mannosyltransferase activity OMP:0005202
4) decreased alpha-1,3-mannosyltransferase activity OMP:0005203
5) abolished alpha-1,3-mannosyltransferase activity OMP:0005204

Thank You for your patience I've been having some computer issues

**Comment by Achchuthan** [comment]
Hi Jesus,

Thanks a lot for the terms. No worries about the delay.

Best wishes,
Achchuthan
