### ISSUE TITLE
Cryptococcus NTR: anaerobic growth phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#92]
NTR
1)	anaerobic growth phenotype

APO cross-refs:
id: APO:0000307
name: anaerobic growth
namespace: observable
def: "Growth in the absence of oxygen." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000210 ! anaerobic metabolism

2)	altered anaerobic growth (is_a anaerobic growth phenotype)
3)	increased anaerobic growth (is_a altered anaerobic growth)
4)	decreased anaerobic growth (is_a altered anaerobic growth)
5)	abolished anaerobic growth (is_a decreased anaerobic growth)
6)	increased rate of anaerobic growth (is_a altered anaerobic growth)
7)	decreased rate of anaerobic growth (is_a altered anaerobic growth)

**Comment by Jguzman210** [comment]
Hi Achchuthan can you please elaborate on what you mean by increased anaerobic growth? Are you referring to an increase in yield (#3) vs an increase in rate (#6)?
Thank You

**Comment by Achchuthan** [comment]
Hi Jesus,

Sorry for the delay in responding back.

That's correct! I refer to increase in yield vs increase in rate.

Many thanks,
Achchuthan

**Comment by Jguzman210** [comment]
Thank you!
I'll get to it ASAP

**Comment by dsiegele** [comment]
Hi Jesus,

I edited the google document on anaerobic growth phenotypes.

Debby 
________________________________________

**Comment by dianeoinglis** [comment]
Please note, there are several terms for Cryptococcus that deal with "growth" and the APO is not consistent or clear when the term is a "growth rate" or a "growth type/mode." As Achchuthan indicates, this refers to rate as the cell number is the quantitative measure of + or - phenotype.

Similarly, yield is another matter that can be described as "production," "formation" and "accumulation." I'd like to be consistent in the OMP as they are not at all consistent in the APO.

Diane

**Comment by Jguzman210** [comment]
Terms made along with OMP #.

1) anaerobic growth phenotype OMP:0005189
2) altered anaerobic growth (is_a anaerobic growth phenotype) OMP: 0005192
3) increased anaerobic growth (is_a altered anaerobic growth) OMP: 0005193
4) decreased anaerobic growth (is_a altered anaerobic growth) OMP: 0005194
5) abolished anaerobic growth (is_a decreased anaerobic growth) OMP: 0005195
6) increased rate of anaerobic growth (is_a altered anaerobic growth) OMP:0005196
7) decreased rate of anaerobic growth (is_a altered anaerobic growth) OMP: 0005197

**Comment by dsiegele** [comment]
I will add terms for increased yield during anaerobic growth.

**Comment by Achchuthan** [comment]
Thanks a lot Jesus for the terms.

**Comment by dsiegele** [comment]
altered yield during anaerobic growth
     increased yield during anaerobic growth
     decreased yield during anaerobic growth
