### ISSUE TITLE
Cryptococcus NTR: autophagic vesicle formation phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#93]
NTR
1)	autophagic vesicle formation phenotype
2)	altered autophagic vesicle formation (is_a autophagic vesicle formation phenotype)
3)	increased autophagic vesicle formation (is_a autophagic vesicle formation)
4)	decreased autophagic vesicle formation (is_a autophagic vesicle formation)
5)	abolished autophagic vesicle formation (is_a autophagic vesicle formation)

**Comment by dsiegele** [comment]
Question: is this the same as an autophagosome?

GO:0005776 ! autophagosome
def: A double-membrane-bounded compartment that engulfs endogenous cellular material as well as invading microorganisms to target them to the vacuole/lysosome for degradation as part of macroautophagy.

**Comment by Achchuthan** [comment]
Hi Debbie,
Autophagic vesicle can either be autophagosome or autolysosome. This could possibly be sued to denote both or the identity is unclear.

Thanks & best wishes,
Achchuthan

**Comment by dsiegele** [comment]
Achchuthan,

I added the following terms to the ontology. Please let me know if these are OK or if changes are needed.

Regards, 
Debby 

 [Term]
id: OMP:0007332
name: cellular process phenotype
def: "A biological process phenotype that affects a cellular process." [OMP:DAS]
comment: This term was created to organize terms beneath it in the ontology. We recommend that it not be used for annotation unless an appropriate child term cannot be found or requested.
xref: FYPO:0000114 "cellular process phenotype"
is_a: OMP:0007194 ! biological process phenotype

[Term]
id: OMP:0007333
name: autophagy phenotype
def: "A cellular process phenotype related to the process of autophagy in which cells digest parts of their own cytoplasm." [GO:0006914, OMP:DAS]
comment: This term was created to organize terms beneath it in the ontology. We recommend that it not be used for annotation unless an appropriate child term cannot be found or requested.
synonym: "autolysosome formation" NARROW []
synonym: "autophagosome formation" NARROW []
is_a: OMP:0007332 ! cellular process phenotype

[Term]
id: OMP:0007334
name: autophagic vesicle formation phenotype
def: "An autophagy phenotype related to the formation of autophagic vesicles." [OMP:DAS]
is_a: OMP:0007333 ! autophagy phenotype

[Term]
id: OMP:0007335
name: altered autophagic vesicle formation
def: "An autophagic vesicle formation phenotype that is altered relative to a designated control." [OMP:DAS]
is_a: OMP:0007334 ! autophagic vesicle formation phenotype

[Term]
id: OMP:0007336
name: increased autophagic vesicle formation
def: "An altered autophagic vesicle formation phenotype where autophagic vesicle formation is increased relative to a designated control." [OMP:DAS]
is_a: OMP:0007335 ! altered autophagic vesicle formation

[Term]
id: OMP:0007337
name: decreased autophagic vesicle formation
def: "An altered autophagic vesicle formation phenotype where autophagic vesicle formation is decreased relative to a designated control." [OMP:DAS]
is_a: OMP:0007335 ! altered autophagic vesicle formation

[Term]
id: OMP:0007338
name: abolished autophagic vesicle formation
def: "A decreased autophagic vesicle formation phenotype where autophagic vesicle formation is abolished." [OMP:DAS]
is_a: OMP:0007337 ! decreased autophagic vesicle formation

**Comment by Achchuthan** [comment]
Thanks a lot Debby for your help.
