### ISSUE TITLE
Cryptococcus NTR: cell fusion phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#97]
NTR
1)	cell fusion phenotype
APO cross-refs:
id: APO:0000033
name: cell fusion
namespace: observable
alt_id: YPO:0000033
def: "The fusion of individual cells from each partner during mating." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000032 ! mating response

2)	altered cell fusion (is_a cell fusion phenotype)
3)	increased cell fusion (is_a altered cell fusion)
4)	decreased cell fusion (is_a altered cell fusion)
5)	abolished cell fusion (is_a decreased cell fusion)
6)	delayed cell fusion (is_a altered cell fusion)

**Comment by dianeoinglis** [comment]
HELLO,

This term must be specified that it occurs during Cryptococcus/fungal mating to distinguish cell fusion that occurs during germ tube or hyphal anastomosis. This may or may not have implications in the parentage.

DIANE

**Comment by dianeoinglis** [comment]
How about "cell fusion during mating phenotype." I also considered "cell-cell fusion." Your judgement call.

Diane

**Comment by Achchuthan** [comment]
All three choices (fungal mating, cell fusion during mating phenotype, cell-cell fusion) appear sensible for me. But, I am inclined to choose either cell fusion during mating phenotype or cell-cell fusion, just to make the terms universal, if possible?

**Comment by dianeoinglis** [comment]
I think "abolished/alterered cell fusion during mating" seems perfect to me.

Diane

**Comment by Jguzman210** [comment]
1) cell fusion phenotype: OMP:0005219	
2) altered cell fusion (is_a cell fusion phenotype): OMP:0005221
3) increased cell fusion (is_a altered cell fusion) OMP:0005222	
4) decreased cell fusion (is_a altered cell fusion) OMP:0005223	
5) abolished cell fusion (is_a decreased cell fusion) OMP:0005224	
6) delayed cell fusion (is_a altered cell fusion) OMP:0005225	
cell fusion during mating phenotype OMP:0005226
absence cell fusion during mating phenotype OMP:0005228 
altered cell fusion during mating phenotype OMP:0005229
abolished cell fusion during mating phenotype OMP:0005232

**Comment by Achchuthan** [comment]
Hi Jesus,

Can I also request another term?
1. delayed cell fusion during mating (is_a: OMP:0005229! altered cell fusion during mating)

Thanks & best wishes,
Achchuthan

**Comment by Jguzman210** [comment]
TR with accesion #
OMP:0005242	delayed cell fusion during mating

Thank You for your patience!!

**Comment by Achchuthan** [comment]
Thanks a lot for your help.

Best wishes,
Achchuthan
