### ISSUE TITLE
Cryptococcus NTR: cell wall morphology phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#98]
NTR
1) cell wall morphology phenotype
is_a: OMP:0000071 ! cell morphology phenotype

APO cross-refs:
id: APO:0000053
name: cell wall morphology
namespace: observable
alt_id: YPO:0000053
def: "The size, shape, or appearance of the cell wall." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000226 ! subcellular morphology

2) altered cell wall morphology (is_a cell wall morphology phenotype)

**Comment by dianeoinglis** [comment]
I think this term should have "cell or cellular morphology phenotype" as a parent term.

Thanks,
Diane

**Comment by Achchuthan** [comment]
Thanks Diane! I have added the parent terms

**Comment by Jguzman210** [comment]
1) cell wall morphology phenotype: OMP:0005233

2) altered cell wall morphology (is_a cell wall morphology phenotype) OMP:0005234
